### ISSUE TITLE
It would be nice to use/see the 'degree sign'

### ISSUE THREAD

**Issue by MiGeppert** [XavierBerger/RPi-Monitor#102]
Hello

It would be nice to use '& deg;' or '& #176;' to show the 'degree sign' (°) in the status and statistics page.
(I think on some positions, '°' is visible, on others you only see '& deg;' or '& #176')
Entering '°' via keyboard doesn't work (for me, I'll get a dummy character).

Best regards
MiGeppert

**Comment by XavierBerger** [comment]
It is  already working.
Degree sign is working fine with `&deg;` in status page as shown in example `dht11.conf`.
If your file is encoded in utf8, you can even use `°` and this also work statistic page .
Check the encoding of your file with the command `file`. You should have something like that:
```
file dht11.conf
dht11.conf: UTF-8 Unicode text
```
Note: I'll update dht11 example and replace `deg` by `°` in next version
