### ISSUE TITLE
errors from syslog on RPi2

### ISSUE THREAD

**Issue by jmgarciamari** [XavierBerger/RPi-Monitor#105]
Hi!, I'm getting this error, and now I can't access throught ssh.

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.620141] Internal error: Oops: 17 [#1] PREEMPT SMP ARM

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.720053] Process rpimonitord (pid: 17641, stack limit = 0xab8c8210)

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.726564] Stack: (0xab8c9d88 to 0xab8ca000)

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.730913] 9d80:                   ab8c9dbc ae6a9bf0 00000000 800edacc ab8c9dbc ab8c9da8

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.739075] 9da0: 800edad8 8005c0b4 ae68c91c ab8c9e5c ab8c9e24 ab8c9dc0 800ee714 800edaa4

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.747237] 9dc0: 00000000 00000000 ab8c9e24 ab8c9dd8 801171d0 76e20000 a9c1c920 ad6b70b0

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.755399] 9de0: 0000014a 00000000 00000001 0000000d 00000040 ab8c9e00 80125544 ad6b70b0

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.763562] 9e00: 000003b7 a086c000 76e2f000 0000001b 00000000 0000001b ab8c9ea4 ab8c9e28

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.771724] 9e20: 80118b4c 800ee5d0 00000000 ae5e8724 25d1d7df 8054d198 a0ab5584 76e2f000

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.779886] 9e40: a0ab5000 ae5ee190 00000040 000000bc 0000002f 00000054 00000000 00000054

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.788048] 9e60: 0000000c 76e20000 00000800 00000008 0000001b a0ab5080 00000000 ab8c9fb0

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.796211] 9e80: 00000017 76e2fa9c ad554e00 a0b74e00 ad554e3c 00000054 ab8c9efc ab8c9ea8

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.804373] 9ea0: 8054d2a0 801183ec 00000000 ae756b70 00000002 20000013 ae756b70 8012000c

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.812535] 9ec0: 20000013 00000000 00000000 00000000 800f47bc 00000017 8054cfc8 76e2fa9c

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.820698] 9ee0: 8080df34 ab8c9fb0 7ebf78d4 00000001 ab8c9fac ab8c9f00 80008424 8054cfd4

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.828860] 9f00: 0004001e ad683900 ad77c600 8013d330 00000000 ad683900 ab8c9f44 ab8c9f28

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.837022] 9f20: 8013d330 80141074 00000000 8013d31c 00020001 a0867e40 ad77c600 8013d330

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.845184] 9f40: 00000000 a0867e40 ab8c9f74 ab8c9f58 8013d330 80141074 00000000 00000004

Message from syslogd@tyrion at Jul 24 12:23:37 ...
 kernel:[10052.853347] 9f60: ad77c600 ad77c640 01014008 00000000 76f9056c 20000010 76f9056c 20000010

**Comment by XavierBerger** [comment]
I can't any evidence showing that **RPi-Monitor** is the root cause of your issue.
