### ISSUE TITLE
Cpu voltage on RPi2 (osmc) shows undefined

### ISSUE THREAD

**Issue by simple-elf** [XavierBerger/RPi-Monitor#112]
Command "vcgencmd measure_volts core" from terminal showing voltage (volt=1.2000V). Regex working ok (i'm also trying "(*.)"). But on web page it still undefined.

Just new RPi and fresh install of osmc and upgrade al packages and kernel to "Linux 4.1.3-2-osmc armv7l".
Nothing changed in rpimonitor config

![image](https://cloud.githubusercontent.com/assets/668395/9079322/57951f1a-3b62-11e5-91d4-543d0b920760.png)

**Comment by simple-elf** [comment]
Ha. Found quick fix.

Changed:
dynamic.2.source=vcgencmd measure_volts core
To:
dynamic.2.source=/opt/vc/bin/vcgencmd measure_volts core

**Comment by XavierBerger** [comment]
This is normal. A FAQ is explaining th reason. I close this issue.

**Comment by ahmedelakkad** [comment]
> 

Where did you change it please?

**Comment by Feriman22** [comment]
@ahmedelakkad in the /etc/rpimonitor/template/cpu.conf file.
