### ISSUE TITLE
Label function evaluates only numbers, not strings

### ISSUE THREAD

**Issue by lpandolfini** [XavierBerger/RPi-Monitor#114]
The Label function defined in file web/js/rpimonitor.utils.js, and used in services.conf works only if the data to be evaluated is a number. This is ok with the examples supplied, but doesn't work if the data returned by the command is a string (for example if I have to check if a service is running).
Simply adding a check to verify if the data is a number does the trick.
The new function is this:
```
function Label(data,formula, text, level){
  var result="";
  if ( level.indexOf('label-') < 0 ) { level = 'label-'+level };
  if ( isNaN(data) ) { data = "\""+data+"\"" };
  eval ( "if ("+data+formula+") result=\"<span class='label "+level+"'>"+text+"</span>\"" );
  return result;
}
```
This will wrap data with double quotes only if it's not a number.
I tested this change in my enbironment and it works.
Thanks

Luca Pandolfini

**Comment by XavierBerger** [comment]
Thanks for this patch. Integration is on going in alert branch
