### ISSUE TITLE
statistic of /boot partition not displayed

### ISSUE THREAD

**Issue by GaetanCambier** [XavierBerger/RPi-Monitor#115]
i haven't statistic for boot partition : 
/boot Used: NaNkB (NaN%) Free: NaNkB Total: NaNkB

detailled statistic also impacted with this error : 
File stat/sdcard_boot_total.rrd is nor a valid RRD file

could you check ?

**Comment by GaetanCambier** [comment]
i have found the problem
i use ubuntu 15.04 and the first partition is not mounted at /boot but /boot/firmware
/dev/mmcblk0p1 on /boot/firmware type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)
i have corrected in the config file and all is ok now :)

**Comment by eddiem5** [comment]
How weird - I have this problem 9 yrs later and don't understand what was updated in the config file as per the post above..
