### ISSUE TITLE
DHT11 undefined values, graph problem

### ISSUE THREAD

**Issue by mistyk** [XavierBerger/RPi-Monitor#127]
Hello,
Thanks for your work ! I've many problem with my temp graph using DHT11, in fact i've sometime undefined values returned by ADAFRUIT, suddenly, I get a chart with values ​​to 0 which is very annoying. Is it possible to not save the value if its undefined ? 
![image](https://cloud.githubusercontent.com/assets/110272/10416785/ccf65692-7024-11e5-9ed8-6ba0389415c5.png)

**Comment by XavierBerger** [comment]
You will find the answer of your question in the FAQ: http://rpi-experiences.blogspot.fr/p/rpi-monitor-faq.html
