### ISSUE TITLE
Export temperature measurements

### ISSUE THREAD

**Issue by Phil1988** [XavierBerger/RPi-Monitor#135]
First: Thanks for this tool.
Also my knowledge is small on linux and the PI I was able to install it on jessie without any issues.

Is it possible to extend the value of temperature mesurements (like every 10 seconds for 3 days) and export the temperature data?
Especially the export function would be great because I want to compare different cooling methods.

It would be great if you can tell me how to do it.
Thanks a lot!

**Comment by XavierBerger** [comment]
Not sure you need RPi-Monitor to do this.
A simple script should be able to answer to your needs.
RPi-Monitor is already performing something close thanks to RRD storage. You can see it in graphs.
