### ISSUE TITLE
OSMC 2015.11-1 "can't find variable"

### ISSUE THREAD

**Issue by srutz26** [XavierBerger/RPi-Monitor#140]
After a fresh install of OSMC 2015.1-1, and after fallowing the install instructions posted I get this when I visit the OSMC RPi-Monitor page:
<img width="2263" alt="screen shot 2016-01-16 at 1 46 18 am" src="https://cloud.githubusercontent.com/assets/7550504/12370991/40446e4e-bbf3-11e5-9a7b-c846c5b39f20.png">
Any idea's/fixes?

**Comment by srutz26** [comment]
I'd also like to mention that I performed the same RPi-Monitor installation my Raspberry Pi 2 Model B running Raspbian Jessie and all is fine and works great. The device running OSMC is also a Raspberry Pi 2 Model B just for reference.

**Comment by XavierBerger** [comment]
It looks like installation didn't work properly. 
The javascript `rpimonitor.utils.js` is gathering all the function marked as missing.
