### ISSUE TITLE
Support for multible columns on larger screen does not work on chrome

### ISSUE THREAD

**Issue by ddyeakley** [XavierBerger/RPi-Monitor#142]
Support for multible columns on larger screen does not work on chrome.   Page displays fine (multible columns) in IE11 but not Chrome (one column).

**Comment by XavierBerger** [comment]
I tried with version 2.11 on google-chrome "Version 52.0.2743.116 (64-bit)" running on Ubuntu 14.04.5 LTS and everthing is working fine...
