### ISSUE TITLE
Repository for Add-Ons

### ISSUE THREAD

**Issue by HoffmannP** [XavierBerger/RPi-Monitor#143]
Is there a repository for add-ons? I'd like to share the ones I developed and reuse some from others…

**Comment by XavierBerger** [comment]
Version 2.11 is not published yet due to bug #136 (and dur to the fact I have no time now to work on it).
If you propose a pull request on devel branch adding your addons contribution, I'll merge it to let other person to benefit to your work.
Thanks.
