### ISSUE TITLE
missing url parameter if only one addon is activated

### ISSUE THREAD

**Issue by maphy-psd** [XavierBerger/RPi-Monitor#146]
I have activated only the custom addon with the url of [pilight](https://www.pilight.org/).

The url in the nav bar of rpimonitor has no "?activePage=0" parameter (http://raspberrypi:8888/addons.htm). I get a blank page. When i manually add ?activePage=0 (http://raspberrypi:8888/addons.html?activePage=0) then i get the pilight webgui.

When i activate two addons, then in the dropdown addon menu of rpimonitor the url parameters "?activePage=0" and "?activePage=1" are set and everything works fine.

I use rpimonitor 2.11 beta.

Greets

**Comment by XavierBerger** [comment]
I just checked with the latest v2.11-beta9.
I confirm that `?activePage=0` is not present when only one add-on is present but it is working.
Can you check if the latest version fix this issue and share your feedbacks?
