### ISSUE TITLE
Graph at statistics shows incorrect values

### ISSUE THREAD

**Issue by mmihal** [XavierBerger/RPi-Monitor#148]
I have tried to create some sipmple  network monitoring tool and monitor packet success of the remote host.

Code looks like this for example:

> dynamic.32.name=google_dns_success
> dynamic.32.source=sudo ping 8.8.8.8 -i 0.01 -c 20 -q
> dynamic.32.regexp=received,\s+(\d+)
> dynamic.32.postprocess=100-$1
> dynamic.32.rrd=GAUGE

data should be only integral numbers but od the statistics graph i can see values in decimal numbers (for example 93.004.) in section 10s(24h total). I do not understand how this is possible.

**Comment by XavierBerger** [comment]
I think this is coming from RRD storage. The RRD database is performing some averages when storing data which could explain what you see.
Refer to RRD web site for details.
