### ISSUE TITLE
updates won't update

### ISSUE THREAD

**Issue by Firemanjoe** [XavierBerger/RPi-Monitor#149]
I must be missing something as i'm not showing 2 updates pending - "pypy-upstream" & "raspberry-pi ui mods". How do I get these to update?

**Comment by MartialDiplomacy** [comment]
Found the solution! Run the following:

`<sudo apt-get update
sudo apt-get install pypy-upstream
sudo apt-get install raspberrypi-ui-mods
sudo apt-get autoremove>`

**Comment by MartialDiplomacy** [comment]
Found the solution! Run the following:

```
sudo apt-get update
sudo apt-get install pypy-upstream
sudo apt-get install raspberrypi-ui-mods
sudo apt-get autoremove
```

**Comment by Firemanjoe** [comment]
worked like a charm! Thanks again!
