### ISSUE TITLE
Not displaying actual CPU frequency.

### ISSUE THREAD

**Issue by simonhowes** [XavierBerger/RPi-Monitor#151]
A little edit to cpu.conf to get the actual CPU frequency:

```
dynamic.1.name=cpu_frequency
dynamic.1.source=vcgencmd measure_clock arm | sed -e "s/frequency(45)=//g"
dynamic.1.postprocess=$1/1000000
dynamic.1.rrd=
```

It'll show throttling on the Pi 3.

**Comment by ghost** [comment]
Useful thanks.

**Comment by XavierBerger** [comment]
Already provided in `cpu.conf` with a simpler command: `/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq`
Closing issue.
