### ISSUE TITLE
Perl 5.24: Experimental push on scalar is now forbidden

### ISSUE THREAD

**Issue by therealbigear** [XavierBerger/RPi-Monitor#157]
After upgrading to Perl 5.24, I get the following Error:
`Experimental push on scalar is now forbidden at /usr/bin/rpimonitord line 178, near "$1) "
BEGIN not safe after errors--compilation aborted at /usr/bin/rpimonitord line 308.`

**Comment by VNovotna** [comment]
Seconding this. I tried to fix it like [here](https://github.com/hitode909/App-PerlPackage2PlantUMLClassDiagram/commit/bf48c554cc5d06e7079daa088a25973c531d5857), but it's more complicated than that and I don't know Perl.

**Comment by Shelvak** [comment]
I don't remember which version of perl I was using. Any idea what version is working well?

**Comment by dorepi** [comment]
I have the same probleme with archlinux.

**Comment by XavierBerger** [comment]
I don't have a PC running Perl 5.24. A pull request is welcome.
I'm about to publish v2.11 in the coming days so pull request on master branch is acceptable.

**Comment by dorepi** [comment]
I believe I have found the solution (It's the first time I try to read perl script) but as I'm not used to github, I'd rather to give you the solution before trying to pull request on master branch.
We have to replace the line 184 of /usr/bin/rpimonitord, 
 `/^include=(.*)/ and -f $1 and push($this->{'daemon'}->{'confFiles'}, $1) and next;`
by
 `/^include=(.*)/ and -f $1 and push(@{$this->{'daemon'}->{'confFiles'}}, $1) and next;`
I hope it's the good way to solve the problem.
Thanks for your awesome program

**Comment by XavierBerger** [comment]
Pull request merged. Thanks for your contribution.
