### ISSUE TITLE
rpimonitord always appears to run as UID 1000 when started with custom config file

### ISSUE THREAD

**Issue by srcshelton** [XavierBerger/RPi-Monitor#160]
(Sorry, can't re-open existing Issues)

Please see [Issue 153](153) -

When invoked as:

```
/usr/sbin/rpimonitord -b /var/run/rpimonitord.pid -c /etc/rpimonitord.conf -c /etc/rpimonitord.conf.d/data.conf
```

... rpimonitord v2.10 seems to ignore the `daemon.{user,group}` directives in `/etc/rpimonitord.conf`.

**Comment by XavierBerger** [comment]
In RPi-Monitor 2.10, the configuration files you define are used in addition with the configuration file provided (/etc/rpimonitor/*.conf). 
In version 2.11, the file you provide overwrite the configuration provided by default.

Can you check that you don't have the file I provide still present and configured?

**Comment by XavierBerger** [comment]
I foud the bug. I did invert user and group so when you use a group/user which as a name different front the user/group (and not existing) it used the default value: 1000
