### ISSUE TITLE
Enhancement: Allow drag-and-drop re-ordering of Status elements

### ISSUE THREAD

**Issue by srcshelton** [XavierBerger/RPi-Monitor#166]
It would be _really_ nice to provide users with the ability to tear-off Status page sections and re-order them, or drop them back into a different position.  Ideally this would be per-user with the current ordering stored via cookies or in browser local storage - but even if the ordering were entirely ephemeral, it would still be helpful.

**Comment by iia** [comment]
Hi there,

Checkout the PR. As of now local storage feature isn't implemented yet but basic sort and reordering.

**Comment by XavierBerger** [comment]
Reordering feature is now implementing `devel` branch and will be part of 2.13 release.
Order is stored and restored in local storage, so per user.
