### ISSUE TITLE
External Drive - Can't get it to display again

### ISSUE THREAD

**Issue by Firemanjoe** [XavierBerger/RPi-Monitor#170]
I just moved into 2.11 and now I can't get my external drive to display again. I attempted to follow the interactive method, but failed after the first command. Do you have suggestions?

**Comment by XavierBerger** [comment]
Suggestion 1: read varefully the doc and check what could be different in your system.
Suggestion 2: use interactive mode `rpimonitord -i` for interactive configuration file creation
