### ISSUE TITLE
Can't locate IPC/ShareLite.pm in @INC

### ISSUE THREAD

**Issue by brunosso** [XavierBerger/RPi-Monitor#171]
I have a Rpi1 and Rpimonitor dont start anymore.

I try to remove rpimonitor with
`apt-get purge rpimonitor`
`rm -fr /etc/rpimonitor`
`rm -fr /usr/share/rpimonitor`
and reinstall but i have always the error...

This dependences are all up to date (librrds-perl libhttp-daemon-perl libjson-perl libipc-sharelite-perl libfile-which-perl)

**Comment by XavierBerger** [comment]
This issue doesn't provide enough info.
Try to start `rpimonitord` manually in verbose mode (ref `man rpimonitord` for command line details)
