### ISSUE TITLE
Serverstatus is not refreshed

### ISSUE THREAD

**Issue by telemaxx** [XavierBerger/RPi-Monitor#172]
With Version 2.7 "Serverstatus Label" was a new feature.
This nice feature only refreshes the label once, at Startup.
eg if i stop the service, the label keeps green.

The command is eg:
netstat -nlt

i want to test with:
```
rpimonitor -i
<ENTER>
netstat -nlt
<ENTER>
<ENTER>

```
nothing happend.

But when i use a command without arguments, it works:
`netstat`

What do i wrong?

Thanks for continue this project,
Thomas

**Comment by dventurino** [comment]
Similar issue here:

If a server goes down the labels do not change to red until rpimonitor is restarted.
But if a server was down and goes up, then the label correctly becomes green.

**Comment by serramat** [comment]
hi everyone,
same problem described by @dventurino even for me :-(

**Comment by telemaxx** [comment]
i solved that problem, i use a cronjob to get the status
check_services.sh

```
#!/bin/sh
/bin/netstat -nlt > /mnt/RAMDisk/netstat.txt
cat /mnt/RAMDisk/netstat.txt|/bin/grep 8200|/usr/bin/wc -l > /mnt/RAMDisk/s_dlna.txt
cat /mnt/RAMDisk/netstat.txt|/bin/grep 8077|/usr/bin/wc -l > /mnt/RAMDisk/s_motion.txt
cat /mnt/RAMDisk/netstat.txt|/bin/grep 8080|/usr/bin/wc -l > /mnt/RAMDisk/s_logview.txt
cat /mnt/RAMDisk/netstat.txt|/bin/grep 8888|/usr/bin/wc -l > /mnt/RAMDisk/s_btsync.txt
cat /mnt/RAMDisk/netstat.txt|/bin/grep  139|/usr/bin/wc -l > /mnt/RAMDisk/s_smb.txt

```

My Ramdisk:

> /mnt/RAMDISK 

/etc/rpimonitor/template/services.conf:

```
dynamic.1.name=dlna
dynamic.1.source=/mnt/RAMDisk/s_dlna.txt

dynamic.2.name=motion
dynamic.2.source=/mnt/RAMDisk/s_motion.txt

dynamic.3.name=Logview
dynamic.3.source=/mnt/RAMDisk/s_logview.txt

dynamic.4.name=BTSync
dynamic.4.source=/mnt/RAMDisk/s_btsync.txt

dynamic.5.name=smb
dynamic.5.source=/mnt/RAMDisk/s_smb.txt

web.status.1.content.1.name=Services
web.status.1.content.1.icon=daemons.png
web.status.1.content.1.line.1=" "+Label(data.dlna,"==1","dlna","success")+Label(data.dlna,"==0","dlna","danger")+" "+Label(data.motion,"==1","motion","succes
s")+Label(data.motion,"==0","motion","danger")+" "+Label(data.BTSync,"==1","BTSync","success")+Label(data.BTSync,"==0","BTSync","danger")+" "+Label(data.smb,
"==2","SAMBA","success")+Label(data.smb,"==0","SAMBA","danger")

```


crontab entry:
`*/1 * * * * /home/pi/scripts/check_services.sh&`

**Comment by Manuel5cc** [comment]
Any news about this? Still not working.

**Comment by serramat** [comment]
I've found a solution a little more easy and I take ssh port for example.
The previous version of /etc/rpimonitor/template/services.conf are:
```
dynamic.1.name=ssh
dynamic.1.source=netstat -nlt
dynamic.1.regexp=tcp .*:(22).*LISTEN

web.status.1.content.1.name=Servers
web.status.1.content.1.icon=daemons.png
web.status.1.content.1.line.1="<b>ssh</b> : "+Label(data.ssh,"==22","OK","success")+Label(data.ssh,"!=22","KO","danger")
```
In my solution became like this
```
dynamic.1.name=ssh
dynamic.1.source=netstat -nlt | grep "tcp .*:22.*LISTEN" | wc -l
dynamic.1.regexp=(\d)

web.status.1.content.1.name=Servers
web.status.1.content.1.icon=daemons.png
web.status.1.content.1.line.1="<b>ssh</b> : "+Label(data.ssh,"==1","OK","success")+Label(data.ssh,"!=1","KO","danger")
```

What do you think about this @XavierBerger ?

**Comment by dventurino** [comment]
I tried @serramat 's approach and it looks good to me.

I changed just the last line a bit:
`web.status.1.content.1.line.1="<b>ssh</b> : "+Label(data.ssh,"==1","OK","success")+Label(data.ssh,"==0","KO","danger")`

**Comment by XavierBerger** [comment]
I found the issue of Interactive mode.
Line 1172: replace `$source =~ /^(.*)/;` by `$source =~ /^(\S+)/;`
This will be fixed in v2.12.

**Comment by dventurino** [comment]
I still encounter this issue with v2.12-r0 with:

```
dynamic.1.name=ssh
dynamic.1.source=netstat -nlt
dynamic.1.regexp=tcp .*:(22).*LISTEN

web.status.1.content.1.name=Servers
web.status.1.content.1.icon=daemons.png
web.status.1.content.1.line.1="<b>ssh</b> : "+Label(data.ssh,"==22","OK","success")+Label(data.ssh,"!=22","KO","danger")
```

It updates from up to down but not from down to up.

**Comment by XavierBerger** [comment]
Solution: 
dynamic.1.default=0

**Comment by dventurino** [comment]
It worked ;) maybe it should be added to the services.conf template ?
