### ISSUE TITLE
rrd database corruption ?

### ISSUE THREAD

**Issue by LilianV** [XavierBerger/RPi-Monitor#174]
Hi,

I use Rpimonitor for months without any problem to display and track many sensors (like temp, pH, EC, waterflow...). I was using python scripts as source but since I began to use more accurate sensors I faced up with problems of "_graphs dropping to 0_". I changed the way of getting data: recording sensors values in MySQL DB (with value check) and getting data from DB with bash scripts. Everything worked until I decided to "reset" graphs by deleting (rm) rrd databases... from that time, the "status" view of my KPI is still working but nothing update in the "statistics" view.

I made some checks with rrdtool and when I ask for "lastupdate" of rrd database, I have confirmation that values are updated but when I ask for "info", the tool return following entry as "last_ds" ligne:

 _"s[xxxxxx].last_ds = "59_

... but i'm waiting for:

_ds[xxxxxx].last_ds = "59"_

I tried everything I could imagine (changing kpi names, graphs, deleting, restoring...) but I'm still stuck...

Thanks for you help.
Lilian

**Comment by XavierBerger** [comment]
**RPi-Monitor** creates the RRD files when it starts.
Restarting it with the command line with verbose flag activated should help to understand the problem.
Note: use `man rpimonitord` to have the list of parameter you can use
