### ISSUE TITLE
Zooming on mobile phones

### ISSUE THREAD

**Issue by telemaxx** [XavierBerger/RPi-Monitor#175]
On my PC in can nicely zoom into a statistic curve.

On my android I cant, I have no mouse for that.

The solution from pimatic is nice and works on touchscreens:

https://usercontent.pimatic.org/3ffba5161f596f03f83714eda2801080c1213dfe/687474703a2f2f7777772e69732e6b656570667265652e64652f323031352d30382d30372d3138353133305f31303234783630305f7363726f742e706e67

What do you think?

**Comment by XavierBerger** [comment]
Changing the engine of **RPi-Monitor** would be a huge work. Plotly is also doing a good job but I don't plan / have time to change the engine of **RPi-Monitor**.
