### ISSUE TITLE
links in topbar are gone

### ISSUE THREAD

**Issue by saveli** [XavierBerger/RPi-Monitor#176]
links in topbar except "About" are gone 
![2017-01-26 16_51_21-rpi-monitor bananapi](https://cloud.githubusercontent.com/assets/18439300/22339131/4c0dbf68-e3e9-11e6-8b64-a96a22559f59.png)

- upgraded from 2.10 to 2.11
- did a apt-get remove and apt-get install, links still missing
- yes, i did update the old repository link to the new repository
- manually typing the adress produces invalid rrd-archive errors like 
![2017-01-26 16_50_58-bananapi_8888 says_](https://cloud.githubusercontent.com/assets/18439300/22339148/56024408-e3e9-11e6-8d27-db90256aaed0.png)

- manually typing the adress again works, even for the previously "erroneous" rrd-archives 
![2017-01-26 16_52_08-rpi-monitor bananapi](https://cloud.githubusercontent.com/assets/18439300/22339159/5c269cbc-e3e9-11e6-85c0-e02bb71a8cc4.png)

**Comment by XavierBerger** [comment]
This should be a problem of configuration.
I would advise to restart from default configuration file and do your conf step by step again to understand where the issue come from.
I would also advise to cleanup the _localstorage_ of your browser (see on your browser help how to do)
