### ISSUE TITLE
Change datastore variable - doesn't change dynamic link?

### ISSUE THREAD

**Issue by csawall** [XavierBerger/RPi-Monitor#180]
Hello.  I'm reviewing all the code to see if I can figure out what's all going on under the hood.  My primary reason is that since I'm running on a RPi2, and RPi-Monitor is using RRD, I wanted to move that directory to a "ram disk" or similar (basically using tmpfs) to limit the writes to disk.  Granted, I'm not sure if that's the only directory store I need to worry about yet?  Thoughts on doing this?  I saw a note in your FAQ that the app was written to take the number of writes into account for a RPi, but I wasn't sure how?

I have that part working fine though (e.g., moved to /mnt/ramdisk/rpimonitor/stat).  However, I noted that if I look in: /usr/share/rpimonitor/web, it still has this dynamic link: stat -> /var/lib/rpimonitor/stat.

Should the code be updated to accommodate for that?  And/or a note in the config file to the user?  Just a thought.  Everything seems to be working w/o changing it though, so I was also looking around to see where that's called.

Thanks!

**Comment by XavierBerger** [comment]
You are right, this symlink is no more needed since I introduce the datastore parameter.
It will be removed from next release. Thanks for the feedback.
