### ISSUE TITLE
possible to run on localhost/rpimonitor?

### ISSUE THREAD

**Issue by molnarti** [XavierBerger/RPi-Monitor#181]
Hi, how can i configure RpiMonitor to be accessible on localhost/rpimonitor instead of localhost:8888? I have tried symlinking the folder /user/share/rpimonitor/web to /var/www but trying to open the address ipadress/rpimonitor just gets me a meesage "Welcome to RPi-Monitor web interface." and a start button. clicking on start shows an empty page. 

Any suggestions? Thanks!

**Comment by XavierBerger** [comment]
**RPi-Monitor** is not designed to do what you are describing here.
On my blog, I do explain how to use nginx as a reverse proxy for security. It should be possible to use such a technique to achieve your goal.
