### ISSUE TITLE
Post Uninstall Errors during Apt-get upgrade

### ISSUE THREAD

**Issue by Pseudomocha** [XavierBerger/RPi-Monitor#184]
Hi, I gave RPi-Monitor a go and found I didn't really need it anymore. I uninstalled it through apt-get remove, and it uninstalled with no errors. However, now whenever I run sudo apt-get upgrade, I get the following:
`Update rpimonitor Packages Status
sh: 1: /usr/share/rpimonitor/scripts/updatePackagesStatus.pl: not found
E: Problem executing scripts DPkg::Post-Invoke 'echo 'Update rpimonitor Packages                                                                                                                       Status' && /usr/share/rpimonitor/scripts/updatePackagesStatus.pl'
E: Sub-process returned an error code
`
What can I do to sort this out? It's pretty annoying to get this error every time I update or install a new package.

**Comment by XavierBerger** [comment]
If you used the latest version, you certainly use the command to install (the optional) package automatic update: 
`/etc/init.d/rpimonitor install_auto_package_status_update`
You should then execute the command ti uninstall this feature:
`/etc/init.d/rpimonitor  remove_auto_package_status_update`
or manually delete the file `/etc/apt/apt.conf.d/99rpimonitor`
