### ISSUE TITLE
Problem with only one addons that is custom

### ISSUE THREAD

**Issue by CharlesGodwin** [XavierBerger/RPi-Monitor#189]
when there is only one addon defined and it is custom, the server does not include the query string activePage=0 so the addons/custom/custom.js script gets null  for activePage when it executes:

**`var activePage = GetURLParameter('activePage');**

The fix is to add this code after that line of code.`

**`if (activePage == null){
   activePage = 0;
}
`**

**Comment by XavierBerger** [comment]
Fix will be part of v2.12. Thanks.
