### ISSUE TITLE
Two  configuration questions/issues

### ISSUE THREAD

**Issue by cderring** [XavierBerger/RPi-Monitor#190]
Hello all,
I hope this package is still being developed as I just found it and find it quite interesting and useful.

Question 1:  Can Temperature be displayed in Imperial rather than metric?  If so, what needs to be configured?  If not, can this be requested as a feature enhancement? 

Question/Issue 2:  There is an article on the RPi-Experience blog about [monitoring WiFi](https://rpi-experiences.blogspot.fr/2013/09/add-wifi-to-raspberry-pi-and-monitor-it.html). That article talks about editing a file for monitoring WiFi but doesn't mention what file.  What file needs to be edited?  IMO reading 13 different articles doesn't really tell me the Linux novice what to edit.

Thank you

**Comment by XavierBerger** [comment]
Question 1: The post process parameter is designed for such a goal.
Question 2: The configuration of RPi-Monitor goes into configuration files which are stored into /etc/rpimonitor/. You will see in this directory a lot of example.

Note: One of the most important command to know in Linux is the command `man`, for RPi-Monitor: `man rpimonitord` or `man rpimonitord.conf` . These commands will answer to all your questions and that is why, I do not specify in the blog where and how to modify file (as it depends on each user...)
