### ISSUE TITLE
incorrect valors for memory and network

### ISSUE THREAD

**Issue by fanabordo** [XavierBerger/RPi-Monitor#192]
hi, how do you get correct valors for memory (Used: NaNkB (NaN%) Available: NaNkB Total: 927.32MB) and network (Used: NaNkB (NaN%) Available: NaNkB) plz? thx by advance

**Comment by martignoni** [comment]
This is a dupe of #191

**Comment by martignoni** [comment]
See https://github.com/XavierBerger/RPi-Monitor/issues/191#issuecomment-324581792 for a partial solution

**Comment by XavierBerger** [comment]
In the latest Raspbian, the parameters of `free` command has changed.
I will fix that in v2.12 - I don't know yet when I'll publish this version but I should do it soon to fix such bugs...

**Comment by ezaul** [comment]
@fanabordo   se estiver usando NTFS   use fuseblk em vez de ntfs 
static.10.source = df -t fuseblk
