### ISSUE TITLE
Official Docker images ?

### ISSUE THREAD

**Issue by Asfalt-FR** [XavierBerger/RPi-Monitor#198]
Hi,
Can you make an official docker version?

**Comment by XavierBerger** [comment]
Fixed : Michael Miklis did a good job. I had a look to his Dockerfile and validate it.
Check my blog for details: [https://rpi-experiences.blogspot.fr/2018/02/rpi-monitor-docker-container.html](https://rpi-experiences.blogspot.fr/2018/02/rpi-monitor-docker-container.html)
