### ISSUE TITLE
Error uninstalling RPi-Monitor

### ISSUE THREAD

**Issue by 97carmine** [XavierBerger/RPi-Monitor#199]
I uninstalled RPi-Monitor using sudo _apt-get purge rpimonitor_ but when executing the _sudo apt-get update_ command, the terminal shows this by screen:

> Update rpimonitor Packages Status
sh: 1: /usr/share/rpimonitor/scripts/updatePackagesStatus.pl: not found
Leyendo lista de paquetes... Hecho
E: Problem executing scripts APT::Update::Post-Invoke 'echo 'Update rpimonitor Packages Status' && /usr/share/rpimonitor/scripts/updatePackagesStatus.pl'

**Comment by XavierBerger** [comment]
You did install the "install_auto_package_status_update" and forgot to uninstall it
You can do it manually with the command `rm /etc/apt/apt.conf.d/99rpimonitor`
I'll label this issue as bug to call  `remove_auto_package_status_update()` when package is uninstalled

**Comment by 97carmine** [comment]
Ok, the problem is solved, thanks

**Comment by XavierBerger** [comment]
Command to remove this `99rpimonitor` file is now present in `prerm` script of **RPi-Monitor** deb package.

**Comment by davide1995** [comment]
2020 and I need to run manually `rm /etc/apt/apt.conf.d/99rpimonitor`

**Comment by JappeHallunken** [comment]
A user on reddit had the same issue, 8 days ago.
[https://www.reddit.com/r/dietpi/comments/tjzgeg/update_problems_after_removing_rpimonitor/](url)
