### ISSUE TITLE
Add link to corresponding graph

### ISSUE THREAD

**Issue by wilbertvolkers** [XavierBerger/RPi-Monitor#201]
Thank you for this project. 

If you like, it is easy to add links on the main page to go to the corresponding graph.

Modify function Start() of "rpimonitor.statistics.js" to read a parameter 'graph':

```javascript
function Start() {
  static = getData('static')
  graphconf = getData('statistics')

  //modified: try read activestat from url
  activestat = GetURLParameter('graph');
  if (activestat == null){
    activestat = localStorage.getItem('activestat') || 0;
  }

  // ... not modified ..
  activePage = GetURLParameter('activePage');
  // ...
}
```
Then modify "uptime.conf" to include a link to the graph:

    # ....
    web.status.1.content.1.name=<a target=_blank href=statistics.html?graph=0>Uptime</a>
    # ....

Same for for cpu.conf (graph=1), temperature.conf (graph=2), etc.

**Comment by XavierBerger** [comment]
New function `LinkToGraph(...)` is now available add this link.
