### ISSUE TITLE
statistics.html gives 'File stat/uptime.rrd is not a valid RRD archive!' after fresh installation

### ISSUE THREAD

**Issue by jnachtigall** [XavierBerger/RPi-Monitor#202]
I installed RPI-Monitor from the Rasbian package, disabled the build-in http server and configured it via apache with
`Alias "/rpimonitor" "/usr/share/rpimonitor/web"`

It works and I can access the web interface via `http://my-raspi-ip/rpimonitor` :-)

However, when I click on `Statistics` then I get the javascript alert: `File stat/uptime.rrd is not a valid RRD archive!`.

![image](https://user-images.githubusercontent.com/3307404/35481459-3740306e-0424-11e8-9b0c-4c6d415cf63f.png)

I looked in the config if I forgot to configure something, but could not find anything. Also on the hard disk for an `stat` directory, but cannot find anything. 

The alert comes from https://github.com/XavierBerger/RPi-Monitor/blob/d096103cc82f6fed16133e037fafcadd8c88f7c7/src/usr/share/rpimonitor/web/js/rpimonitor.statistics.js#L95

Any idea what's wrong?

**Comment by jnachtigall** [comment]
ok, got it working with:
`sudo ln -s /var/lib/rpimonitor/stat /usr/share/rpimonitor/web/stat`

**Comment by XavierBerger** [comment]
Fixed in devel branch
