### ISSUE TITLE
addons top3 display undefined

### ISSUE THREAD

**Issue by jepiclo** [XavierBerger/RPi-Monitor#206]
J'ai activé le plugin dans data.conf et le resultat est undefined sur la page add-ons ==> top3.
Sinon super boulot, merci

**Comment by XavierBerger** [comment]
The bug report is Incomplete . To use addons I suggest to following link. 
https://rpi-experiences.blogspot.fr/2015/01/rpi-monitor-version-210-is-available.html

**Comment by XavierBerger** [comment]
You are lucky, I'm working on the documentation and I'm just starting to review addons.

Try that:
```
  web.addons.2.name=Top3
  web.addons.2.addons=top3
```
I replaced 5 by 2. The `id` in addons is important and should start by 1 and incrementing. If you commented out the example addons, `id` should be 1.

**Comment by jepiclo** [comment]
Youpiiiiii
Merci beaucoup

2018-02-20 15:32 GMT-03:00 Xavier Berger <notifications@github.com>:
