### ISSUE TITLE
Installation links are broken

### ISSUE THREAD

**Issue by JohanSF** [XavierBerger/RPi-Monitor#213]
https://xavierberger.github.io/RPi-Monitor-docs/11_installation.html

http://goo.gl/vewCLL is broken, so I can't install.

**Comment by XavierBerger** [comment]
I just click on you link and I've got exactly what I was expecting. 
```
# RPi-Monitor official repository
deb http://giteduberger.fr rpimonitor/
```
I just retest the procedure right now and everything looks right...
I think your issue is somewhere else...

**Comment by JohanSF** [comment]
http://goo.gl/vewCLL gives me "This site can’t be reached, goo.gl refused to connect."

so it's at this step I get an error on the pi:
`sudo wget http://goo.gl/vewCLL -O /etc/apt/sources.list.d/rpimonitor.list`

**Comment by XavierBerger** [comment]
The problem is located into your network.
Copy the content of the file shown upper into the file `/etc/apt/sources.list.d/rpimonitor.list` and continue the procedure. This should fix your issue.
