### ISSUE TITLE
Undefined value on correct voltage reading

### ISSUE THREAD

**Issue by x2k13** [XavierBerger/RPi-Monitor#215]
Finally my Pi 3 B+ arrived and so I thought I'd make a fresh start with my media center. 
Running latest OSMC version (2018.03-2):
[https://osmc.tv/2018/03/osmcs-march-update-is-here-with-pi-3-b-support/](url)

After installing rpimonitor I noticed under the "Voltage" entry there's just a "undefined" value.
![8491bc7e-819c-4fd2-8530-df9d0065d176](https://user-images.githubusercontent.com/13673423/38326772-f08a5ba2-3846-11e8-8b8d-f513d45ef7d4.png)
the ./cpu.conf  is untouched:
```
dynamic.2.name=cpu_voltage
dynamic.2.source=vcgencmd measure_volts core
dynamic.2.regexp=(\d+.\d+)V
dynamic.2.postprocess=
dynamic.2.rrd=
```
When I issue the command on console, I get the correct value:
```
vcgencmd measure_volts core
volt=1.2000V
```
I have no idea what's wrong with that, I already tried several regex variants but to no avail.

**Comment by avma** [comment]
Hi,
I reinstalled  rpimonitor_latest.deb on a rpi B, rpi2 b and rpi3 b, Raspbian Stretch. Temperature is not showing on both, temperature.conf was untouched...(voltage does shows for me)

![image](https://user-images.githubusercontent.com/7680483/38417649-ce23f292-39a1-11e8-8303-a7f82498d769.png)

My regards
Avi

**Comment by x2k13** [comment]
Meanwhile, OSMC got an update to version 2018.04-2, but the issue still persists.
I still can't get RPi-Monitor to display voltage values.

**Comment by Leepic** [comment]
@x2k13 can you give me the whole config file?

**Comment by x2k13** [comment]
@Leepic
Sorry, there hasn't been any response to this issue by the Dev in months. Meanwhile I switched to NetData and ditched all Rpi-Monitor files. Can't help with that anymore, so I'm closing this now.
