### ISSUE TITLE
RPI monitor does not response on port

### ISSUE THREAD

**Issue by hacsko-adam** [XavierBerger/RPi-Monitor#220]
I recently installed RPi-Monitor on my rpi 3B followed the steps given. When i try to load the page i can see the following error message: 

    Can't locate URI/http.pm:   /usr/local/lib/arm-linux-gnueabihf/perl/5.24.1/URI/http.pm: Permission denied at (eval 25) line 2.

I have checked, that library and file does not exists on my system. 
Could someone advised, what is missing and how to fix it?

**Comment by SuperSandro2000** [comment]
Looks like you miss perl

**Comment by hacsko-adam** [comment]
I already installed Perl like the guide said
![pi](https://user-images.githubusercontent.com/10884684/39209756-02d60ebc-4807-11e8-915b-50b3eff91a2b.jpg)

**Comment by Leepic** [comment]
You need to install two packages for Perl URI::HTTP module:

```
sudo apt-get install libregexp-common-perl
sudo apt-get install liburi-perl
```
I'm on a RPi 3B too and I have this packages installed.

**Comment by Leepic** [comment]
@hacsko-adam : is this issue still persists after the installation of the missing packages?

**Comment by XavierBerger** [comment]
non answer to leepic question: closing
