### ISSUE TITLE
Impossible to monitor a wifi network since writing to /sys is impossible

### ISSUE THREAD

**Issue by RandomGuyJCI** [XavierBerger/RPi-Monitor#221]
I can't make, edit, or save the dynamic.conf file to the correct directory, since I can't modify any of /sys, even with root permission. I tried chmod too, but it also doesn't work,

**Comment by Leepic** [comment]
Can you give me an example? I don't have any dynamic.conf file.
What do you mean by "the correct directory"? Which one?
