### ISSUE TITLE
RPi-Monitor not working

### ISSUE THREAD

**Issue by 3Domse3** [XavierBerger/RPi-Monitor#228]
I installed, deleted and reinstalled it exactly as written in the documentation and it still isn't working. It is shown in the installed package list but no website is reachable. Even with a port scan, I can only find "ssh" and "vnc". Is there a way to manually start the server?

**Comment by XavierBerger** [comment]
```rpimonitord``` and add  ```-v```  to encreare verbosity. Multiply the number of ```v``` to encrease the log level.
