### ISSUE TITLE
Servers list is not updated unless I restart rpimonitor service

### ISSUE THREAD

**Issue by dperrenoud** [XavierBerger/RPi-Monitor#232]
Hello,
Congratulations for this great application.
I enabled Servers monitoring by uncommenting this line:
include=/etc/rpimonitor/template/services.conf

The server's OK or KO status is not automatically updated. However, if I manually restart rpimonitor, Server's status is updated. I added a few servers to monitor in services.conf.

Many thanks.

**Comment by XavierBerger** [comment]
This is the normal behaviour of the application. Closing issue.

**Comment by dperrenoud** [comment]
You probably misunderstood my remark. Anyway. Thanks for your very kind and detailed response. Have a nice evening!

**Comment by telemaxx** [comment]
same like in #172 there is also a solution.
