### ISSUE TITLE
how to solve these issues??

### ISSUE THREAD

**Issue by platini76** [XavierBerger/RPi-Monitor#234]
<img width="1672" alt="schermata 2018-07-30 alle 17 54 43" src="https://user-images.githubusercontent.com/10352902/43408526-e3f43002-9421-11e8-9d3b-de76a98b6b1f.png">

**Comment by licaon-kter** [comment]
How do you run?

**Comment by XavierBerger** [comment]
RPi-Monitor is a tool designed to be configured and customized to match your need. Configuration file provided are here as example. Refer to documentation to fix your issue.
