### ISSUE TITLE
Wrong number of processors

### ISSUE THREAD

**Issue by castillo92** [XavierBerger/RPi-Monitor#240]
In the file:
`/etc/rpimonitor/template/cpu.conf
`

we can see:
```
static.5.name=max_proc
static.5.source=nproc
static.5.regexp=(.*)
static.5.postprocess=$1 + 1   <-----
```

the proper code should be:
```
static.5.name=max_proc
static.5.source=nproc
static.5.regexp=(.*)
static.5.postprocess=$1          <-----
```
Because if not, the monitor tell us that the maximun load of CPU is 5 instead of 4

Board: Raspberry Pi 2 B

**Comment by Leepic** [comment]
+1. Same for me on a RPi 3B.

```
grep processor /proc/cpuinfo 
processor	: 0
processor	: 1
processor	: 2
processor	: 3
```

RPi-Monitor indicate that is 5 instead of 4:

![image-rpimonitor-wrong-max-cpu-number](https://user-images.githubusercontent.com/10730819/50712653-9003e000-1072-11e9-9e83-47d44876aa4b.png)

Can you submit a pull request?

**Comment by castillo92** [comment]
> +1. Same for me on a RPi 3B.
> 
> ```
> grep processor /proc/cpuinfo 
> processor	: 0
> processor	: 1
> processor	: 2
> processor	: 3
> ```
> RPi-Monitor indicate that is 5 instead of 4:
> 
> ![image-rpimonitor-wrong-max-cpu-number](https://user-images.githubusercontent.com/10730819/50712653-9003e000-1072-11e9-9e83-47d44876aa4b.png)
> 
> Can you submit a pull request?

I just did it.

The number of CPU cores are:
`
grep processor /proc/cpuinfo 
processor	: 0
processor	: 1
processor	: 2
processor	: 3
`

But the output of command "nproc" is 4

**Comment by Leepic** [comment]
>I just did it.

I can't see your pull request.


>The number of CPU cores are:
>grep processor /proc/cpuinfo processor : 0 processor : 1 processor : 2 processor : 3

>But the output of command "nproc" is 4

Same for me. The two commands are true.

**Comment by castillo92** [comment]
> > I just did it.
> 
> I can't see your pull request.
> 
> > The number of CPU cores are:
> > grep processor /proc/cpuinfo processor : 0 processor : 1 processor : 2 processor : 3
> 
> > But the output of command "nproc" is 4
> 
> Same for me. The two commands are true.

Sorry, but I created a fork in my profile. I try to create a Pull Request but I can not edit the file:

https://github.com/XavierBerger/RPi-Monitor/blob/develop/src/etc/rpimonitor/template/cpu.conf

Line 63

**Comment by Leepic** [comment]
It's because your branch is not up-to-date with this one. First you need to compare and merge if there are no conflict. After you will be able to edit cpu.conf and submit your pull request :).

**Comment by moddok** [comment]
I dont think thats a problem. the 5 is not the count of your cores, but the load of the cpu.
and the load can be bigger than 4.

**Comment by Leepic** [comment]
@moddok : it's not a real problem, it's only the display.

You're right, the load can be bigguest than the number of CPU cores but if your load is 5 and you only have 4 cores (physical and logical), the number 5 will be displayed with a red gauge (that indicate a problem).

I don't see a reason of the + 1 in the calcul.
