### ISSUE TITLE
CPU temperature is NULL on RPI2B or RPI3B

### ISSUE THREAD

**Issue by thc2018** [XavierBerger/RPi-Monitor#245]
Temperature
CPU Temperature
0
null°C

How can i fixed it?

**Comment by castillo92** [comment]
Try editing the CPU Template, I include temperatures in it:


sudo nano /etc/rpimonitor/template/cpu.conf


```
dynamic.1.name=cpu_frequency
dynamic.1.source=/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq
dynamic.1.regexp=(.*)
dynamic.1.postprocess=$1/1000
dynamic.1.rrd=

dynamic.2.name=cpu_voltage
dynamic.2.source=vcgencmd measure_volts core
dynamic.2.regexp=(\d+.\d+)V
dynamic.2.postprocess=
dynamic.2.rrd=

dynamic.3.name=load1,load5,load15
dynamic.3.source=/proc/loadavg
dynamic.3.regexp=^(\S+)\s(\S+)\s(\S+)
dynamic.3.postprocess=
dynamic.3.rrd=GAUGE

dynamic.4.name=scaling_governor
dynamic.4.source=/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
dynamic.4.regexp=(.*)
dynamic.4.postprocess=
dynamic.4.rrd=

static.5.name=max_proc
static.5.source=nproc
static.5.regexp=(.*)
static.5.postprocess=$1

dynamic.6.name=soc_temp
dynamic.6.source=/sys/devices/virtual/thermal/thermal_zone0/temp
dynamic.6.regexp=(.*)
dynamic.6.postprocess=sprintf("%.1f", $1/1000)
dynamic.6.rrd=GAUGE


web.status.1.content.1.name=CPU
web.status.1.content.1.icon=cpu.png
#web.status.1.content.1.line.1="Loads: <b>" + data.load1 + "</b> [1min] - <b>" + data.load5 + "</b> [5min] - <b>" + data.load15 + "</b> [15min]"
web.status.1.content.1.line.1=JustGageBar("Load", "1min", 0, data.load1, data.max_proc, 100, 80)+" "+JustGageBar("Load", "5min", 0, data.load5, data.max_proc, 100, 80)+" "+JustGageBar("Load", "15min", 0, data.load15, data.max_proc, 100, 80)
web.status.1.content.1.line.2=JustGageBar("CPU Temperature", "°C", 40, data.soc_temp, 80, 100, 80)
web.status.1.content.1.line.3="CPU frequency: <b>" + data.cpu_frequency + "MHz</b> Voltage: <b>" + data.cpu_voltage + "V</b>"
web.status.1.content.1.line.4="Scaling governor: <b>" + data.scaling_governor + "</b>"
#web.status.1.content.1.line.5=InsertHTML("/addons/top3/top3.html")

web.statistics.1.content.1.name=CPU Loads
web.statistics.1.content.1.graph.1=load1
web.statistics.1.content.1.graph.2=load5
web.statistics.1.content.1.graph.3=load15
web.statistics.1.content.1.ds_graph_options.load1.label=Load 1min
web.statistics.1.content.1.ds_graph_options.load5.label=Load 5min
web.statistics.1.content.1.ds_graph_options.load15.label=Load 15min
web.statistics.1.content.2.name=Temperature
web.statistics.1.content.2.graph.1=soc_temp
web.statistics.1.content.2.ds_graph_options.soc_temp.label=Core temperature (°C)
```

**Comment by Leepic** [comment]
@thc2018 what's the output of this command `cat /sys/devices/virtual/thermal/thermal_zone0/temp`?

**Comment by thc2018** [comment]
@castillo92 , still NULL

@Leepic 
`cat /sys/devices/virtual/thermal/thermal_zone0/temp
26792`

**Comment by Leepic** [comment]
I can confirm that the configuration of @castillo92 also works for me on Raspbian 8 Lite (jessie) with a RaspberryPi 3B and RPi-Monitor v2.12-r0.

@thc2018 can you give us your configuration file?
Did you try to modify `dynamic.6.source=/sys/devices/virtual/thermal/thermal_zone0/temp` with for example `dynamic.6.source=/tmp/issue245` with the value `26792` in the file `/tmp/issue245` and then restart rpimonitor?

**Comment by castillo92** [comment]
> I can confirm that the configuration of @castillo92 also works for me on Raspbian 8 Lite (jessie) with a RaspberryPi 3B and RPi-Monitor v2.12-r0.
> 
> @thc2018 can you give us your configuration file?
> Did you try to modify `dynamic.6.source=/sys/devices/virtual/thermal/thermal_zone0/temp` with for example `dynamic.6.source=/tmp/issue245` with the value `26792` in the file `/tmp/issue245` and then restart rpimonitor?

Thanks you for the confirmation

**Comment by thc2018** [comment]
My /etc/rpimonitor/template/cpu.conf
----------------------------------------------
```
########################################################################
# Extract CPU information
#  Page: 1
#  Information               Status     Statistics
#  - cpu frequency           - yes      - no
#  - cpu voltage             - yes      - no
#  - cpu load 1, 5, 15       - yes      - yes
#  - cpu scaling governor    - yes      - no
########################################################################
#dynamic.1.name=cpu_frequency
#dynamic.1.source=/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq
#dynamic.1.regexp=(.*)
#dynamic.1.postprocess=$1/1000
#dynamic.1.rrd=
#snmp.cpu_frequency.id=7
#snmp.cpu_frequency.type=integer
#snmp.cpu_frequency.description=cpu_frequency
#snmp.cpu_frequency.postprocess=

#dynamic.2.name=cpu_voltage
#dynamic.2.source=vcgencmd measure_volts core
#dynamic.2.regexp=(\d+.\d+)V
#dynamic.2.postprocess=
#dynamic.2.rrd=
#snmp.cpu_voltage.id=8
#snmp.cpu_voltage.type=integer
#snmp.cpu_voltage.description=cpu_voltage
#snmp.cpu_voltage.postprocess=$1*100

#dynamic.3.name=load1,load5,load15
#dynamic.3.source=/proc/loadavg
#dynamic.3.regexp=^(\S+)\s(\S+)\s(\S+)
#dynamic.3.postprocess=
#dynamic.3.rrd=GAUGE
#snmp.load1.id=9
#snmp.load1.type=integer
#snmp.load1.description=load1
#snmp.load1.postprocess=$1*100
#snmp.load5.id=10
#snmp.load5.type=integer
#snmp.load5.description=load5
#snmp.load5.postprocess=$1*100
#snmp.load15.id=11
#snmp.load15.type=integer
#snmp.load15.description=load15
#snmp.load15.postprocess=$1*100

#dynamic.4.name=scaling_governor
#dynamic.4.source=/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
#dynamic.4.regexp=(.*)
#dynamic.4.postprocess=
#dynamic.4.rrd=
#snmp.scaling_governor.id=12
#snmp.scaling_governor.type=string
#snmp.scaling_governor.description=scaling_governor
#snmp.scaling_governor.postprocess=

#static.1.name=max_proc
#static.1.source=nproc
#static.1.regexp=(.*)
#static.1.postprocess=$1 + 1

#web.status.1.content.1.title="CPU"
#web.status.1.content.1.icon=cpu.png
#web.status.1.content.1.line.1="Loads: <b>" + data.load1 + "</b> [1min] - <b>" + data.load5 + "</b> [5min] - <b>" + data.load15 + "</b> [15min]"
#web.status.1.content.1.line.1=JustGageBar("Load", "1min", 0, data.load1, data.max_proc, 100, 80)+" "+JustGageBar("Load", "5min", 0, data.load5, data.max_proc, 100, 80)+" "+JustGageBar("Load", "15min", 0, data.load15, data.max_proc, 100, 80)
#web.status.1.content.1.line.2="CPU frequency: <b>" + data.cpu_frequency + "MHz</b> Voltage: <b>" + data.cpu_voltage + "V</b>"
#web.status.1.content.1.line.3="Scaling governor: <b>" + data.scaling_governor + "</b>"
#web.status.1.content.1.line.4=InsertHTML("/addons/top3/top3.html")

#web.statistics.1.content.1.title="CPU Loads"
#web.statistics.1.content.1.graph.1=load1
#web.statistics.1.content.1.graph.2=load5
#web.statistics.1.content.1.graph.3=load15
#web.statistics.1.content.1.ds_graph_options.load1.label=Load 1min
#web.statistics.1.content.1.ds_graph_options.load5.label=Load 5min
#web.statistics.1.content.1.ds_graph_options.load15.label=Load 15min
dynamic.1.name=cpu_frequency
dynamic.1.source=/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq
dynamic.1.regexp=(.*)
dynamic.1.postprocess=$1/1000
dynamic.1.rrd=

dynamic.2.name=cpu_voltage
dynamic.2.source=vcgencmd measure_volts core
dynamic.2.regexp=(\d+.\d+)V
dynamic.2.postprocess=
dynamic.2.rrd=

dynamic.3.name=load1,load5,load15
dynamic.3.source=/proc/loadavg
dynamic.3.regexp=^(\S+)\s(\S+)\s(\S+)
dynamic.3.postprocess=
dynamic.3.rrd=GAUGE

dynamic.4.name=scaling_governor
dynamic.4.source=/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
dynamic.4.regexp=(.*)
dynamic.4.postprocess=
dynamic.4.rrd=

static.5.name=max_proc
static.5.source=nproc
static.5.regexp=(.*)
static.5.postprocess=$1

dynamic.6.name=soc_temp
dynamic.6.source=/sys/devices/virtual/thermal/thermal_zone0/temp
dynamic.6.regexp=(.*)
dynamic.6.postprocess=sprintf("%.1f", $1/1000)
dynamic.6.rrd=GAUGE


web.status.1.content.1.name=CPU
web.status.1.content.1.icon=cpu.png
#web.status.1.content.1.line.1="Loads: <b>" + data.load1 + "</b> [1min] - <b>" + data.load5 + "</b> [5min] - <b>" + data.load15 + "</b> [15min]"
web.status.1.content.1.line.1=JustGageBar("Load", "1min", 0, data.load1, data.max_proc, 100, 80)+" "+JustGageBar("Load", "5min", 0, data.load5, data.max_proc, 100, 80)+" "+JustGageBar("Load", "15min", 0, data.load15, data.max_proc, 100, 80)
web.status.1.content.1.line.2=JustGageBar("CPU Temperature", "°C", 40, data.soc_temp, 80, 100, 80)
web.status.1.content.1.line.3="CPU frequency: <b>" + data.cpu_frequency + "MHz</b> Voltage: <b>" + data.cpu_voltage + "V</b>"
web.status.1.content.1.line.4="Scaling governor: <b>" + data.scaling_governor + "</b>"
#web.status.1.content.1.line.5=InsertHTML("/addons/top3/top3.html")

web.statistics.1.content.1.name=CPU Loads
web.statistics.1.content.1.graph.1=load1
web.statistics.1.content.1.graph.2=load5
web.statistics.1.content.1.graph.3=load15
web.statistics.1.content.1.ds_graph_options.load1.label=Load 1min
web.statistics.1.content.1.ds_graph_options.load5.label=Load 5min
web.statistics.1.content.1.ds_graph_options.load15.label=Load 15min
web.statistics.1.content.2.name=Temperature
web.statistics.1.content.2.graph.1=soc_temp
web.statistics.1.content.2.ds_graph_options.soc_temp.label=Core temperature (°C)
----------------------------------------------
```

**Comment by thc2018** [comment]
@Leepic , still 0 NULL

conf modified:
`dynamic.6.source=/tmp/issue245 #/sys/devices/virtual/thermal/thermal_zone0/temp`

and value set:
`$ tail /tmp/issue245
26792
`

![image](https://user-images.githubusercontent.com/41195917/50722969-48b83680-10e8-11e9-8259-fb4b1f824b64.png)

**Comment by castillo92** [comment]
> @Leepic , still 0 NULL
> 
> conf modified:
> `dynamic.6.source=/tmp/issue245 #/sys/devices/virtual/thermal/thermal_zone0/temp`
> 
> and value set:
> `$ tail /tmp/issue245 26792 `
> 


You are using my template, and I added the CPU Temperature indicator inside "CPU" tab


<a href="https://i.imgur.com/NTszM6y.png"><img src="https://i.imgur.com/NTszM6y.png" title="source: imgur.com" /></a>

**Comment by thc2018** [comment]
![image](https://user-images.githubusercontent.com/41195917/50724589-33033b00-1101-11e9-82ff-7c544a94e947.png)

0 (

**Comment by thc2018** [comment]
![image](https://user-images.githubusercontent.com/41195917/50724618-b4f36400-1101-11e9-8528-e776026d2119.png)

0 (

**Comment by castillo92** [comment]
> ![image](https://user-images.githubusercontent.com/41195917/50724618-b4f36400-1101-11e9-8528-e776026d2119.png)
> 
> 0 (

I do not know what is happening in your Raspberry. So.... You tried....?

`cat /sys/devices/virtual/thermal/thermal_zone0/temp`

And the output is: NULL ?

**Comment by thc2018** [comment]
`cat /sys/devices/virtual/thermal/thermal_zone0/temp`

output is `34234`

**Comment by castillo92** [comment]
> `cat /sys/devices/virtual/thermal/thermal_zone0/temp`
> 
> output is `34234`

Ouch! It works! **34234/1000 = 34.2ºC** 

So.... RPi-Monitor is having troubles to obtain that number. We are going to try the wizard to obtain the code:

### Open your console and type:
`rpimonitord -i`

### You will see:
```
**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 RPi-Monitor Interactive is a tool to help you to define the
 parameter of the configuration file: source, regexp, postprocess
 and type

 Press [Enter] to continue:
```
##### So **press Enter**

### Now you will see:
```
**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 First you have to define the source. The source can be a file or a
 command to be executed.

 If source is a command, RPi-Monitor executes this command and parse
 <STDOUT>. If you need to parse <STDERR> add 2>&1 at the end of the
 command to redirect <STDERR> to <STDOUT>.

 If the source is a flat file, RPi-Monitor parses it line by line.

 Enter here the command or the file to use as source []:
```
### Write the location of file which store the temperature and press Enter
`/sys/devices/virtual/thermal/thermal_zone0/temp
`

### You will see:
```
**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 '/sys/devices/virtual/thermal/thermal_zone0/temp' is a flat file
 Is that correct? Yes/No [Yes]:
```
##### So press Enter, because is right

### Now we are going to write the filter:
##### It is not neccesary because the file store only the temperature number
```
**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 The Regular Expression is here to extract the information from the
 source. To learn Perl Regular Expression you can refer to the
 documentation: http://perldoc.perl.org/perlretut.html
 It is required to put the value to extract into parenthesis.

 Enter your regular expression /(.*)/:
```
### So press Enter

### Now, RPi-Monitor will show the data found:
```
**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 Applying the Regular Expression '(.*)'
 on the source '/sys/devices/virtual/thermal/thermal_zone0/temp' gives the following result:

 $1 = 56920

 Is that correct? Yes/No [No]:
```
##### If you can see the numbers, type "Yes" and press Enter

### Now, RPi-Monitor ask you to apply a formula. We have to divide the number by 1000
```
**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 The post processing formula is designed to adjust the value extracted
 by the regular expression. This value is accessible using $1


 Enter your formula []:
```
### So type:
`$1/1000
`
##### The $1 mean the number readed before

### You will see:
```
**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 After applying the post precessing formule, the result is:

56.382

 Is that correct? Yes/No [No]:
```
##### Now we can see the temperature in the right form

### Finally ask us:
```
**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 RPi-Monitor manage 2 types of data; static or dynamic.
 static data are not changing over the time like disk size.
 dynamic data can change over the time like disk usage.

 Is is a static data? [Yes]
```
##### Tipe **No** because it is a dynamic value.

And the final step is see the code:
```
**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 We have now defined all the parameters allowing RPi-Monitor to
 extract the data from the system. Here is a template of configuration
 base on your actual configuration.

dynamic.35.name=<Add here the name>
dynamic.35.source=/sys/devices/virtual/thermal/thermal_zone0/temp
dynamic.35.regexp=(.*)
dynamic.35.postprocess=$1/1000
dynamic.35.rrd=<Define the rrd type>

 You now have to copy it into an existing configuration file or
 add anew file into /etc/rpimonitor/.
 <Note the some text require a manual update>
 Once the configuration will be apply, restart RPi-Monitor with the
 command: /etc/init.d/rpimonitor restart or systemctl restart rpimonitord
```
### Copy and paste in your CPU.conf the text above:
> dynamic.35.name=<Add here the name>
> dynamic.35.source=/sys/devices/virtual/thermal/thermal_zone0/temp
> dynamic.35.regexp=(.*)
> dynamic.35.postprocess=$1/1000
> dynamic.35.rrd=<Define the rrd type>

### Or rewrite 

> dynamic.6.name=soc_temp
> dynamic.6.source=/sys/devices/virtual/thermal/thermal_zone0/temp
> dynamic.6.regexp=(.*)
> dynamic.6.postprocess=sprintf("%.1f", $1/1000)
> dynamic.6.rrd=GAUGE


If you see, the line dynamic.6.postprocess=**sprintf("%.1f",** $1/1000) have a command who it is not needed. Probably your fault is that.

**Comment by thc2018** [comment]
I`ve performed all steps, and on every step everything was successful.

`$ rpimonitord -i
**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 RPi-Monitor Interactive is a tool to help you to define the
 parameter of the configuration file: source, regexp, postprocess
 and type

 Press [Enter] to continue:
`**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 First you have to define the source. The source can be a file or a
 command to be executed.

 If source is a command, RPi-Monitor executes this command and parse
 <STDOUT>. If you need to parse <STDERR> add 2>&1 at the end of the
 command to redirect <STDERR> to <STDOUT>.

 If the source is a flat file, RPi-Monitor parses it line by line.

 Enter here the command or the file to use as source []:
 /sys/devices/virtual/thermal/thermal_zone0/temp
`
`**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 '/sys/devices/virtual/thermal/thermal_zone0/temp' is a flat file
 Is that correct? Yes/No [Yes]: Yes
`
`**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 The Regular Expression is here to extract the information from the
 source. To learn Perl Regular Expression you can refer to the
 documentation: http://perldoc.perl.org/perlretut.html
 It is required to put the value to extract into parenthesis.

 Enter your regular expression /(.*)/:`

`**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 Applying the Regular Expression '(.*)'
 on the source '/sys/devices/virtual/thermal/thermal_zone0/temp' gives the following result:

 $1 = 34862

 Is that correct? Yes/No [No]: Yes
`
`**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 The post processing formula is designed to adjust the value extracted
 by the regular expression. This value is accessible using $1


 Enter your formula []:$1/1000
`
`**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 After applying the post precessing formule, the result is:

34.862

 Is that correct? Yes/No [No]: Yes
`
`**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 RPi-Monitor manage 2 types of data; static or dynamic.
 static data are not changing over the time like disk size.
 dynamic data can change over the time like disk usage.

 Is is a static data? [Yes]No
`
`**********************************************************************
*           RPi-Monitor Interactive Configuration Helper             *
**********************************************************************
 We have now defined all the parameters allowing RPi-Monitor to
 extract the data from the system. Here is a template of configuration
 base on your actual configuration.

dynamic.17.name=<Add here the name>
dynamic.17.source=/sys/devices/virtual/thermal/thermal_zone0/temp
dynamic.17.regexp=(.*)
dynamic.17.postprocess=$1/1000
dynamic.17.rrd=<Define the rrd type>

 You now have to copy it into an existing configuration file or
 add a new file into /etc/rpimonitor/.
 <Note the some text require a manual update>
 Once the configuration will be apply, restart RPi-Monitor with the
 command: /etc/init.d/rpimonitor restart or systemctl restart rpimonitord`
--------------------------------------------
I have tried this in /etc/rpimonitor/template/cpu.conf:
`dynamic.6.name=soc_temp
dynamic.6.source=/sys/devices/virtual/thermal/thermal_zone0/temp
dynamic.6.regexp=(.*)
dynamic.6.postprocess=sprintf("%.1f", $1/1000)
dynamic.6.rrd=GAUGE`

and this:
`dynamic.6.name=soc_temp
dynamic.6.source=/sys/devices/virtual/thermal/thermal_zone0/temp
dynamic.6.regexp=(.*)
dynamic.6.postprocess=$1/1000
dynamic.6.rrd=GAUGE`

And still 0:
![image](https://user-images.githubusercontent.com/41195917/50817922-86aa9a00-1336-11e9-8a53-8ac463e39244.png)

**Comment by castillo92** [comment]
> I`ve performed all steps, and on every step everything was successful.
> Once the configuration will be apply, restart RPi-Monitor with the
> command: /etc/init.d/rpimonitor restart or systemctl restart rpimonitord`
> I have tried this in /etc/rpimonitor/template/cpu.conf:
> `dynamic.6.name=soc_temp dynamic.6.source=/sys/devices/virtual/thermal/thermal_zone0/temp dynamic.6.regexp=(.*) dynamic.6.postprocess=sprintf("%.1f", $1/1000) dynamic.6.rrd=GAUGE`
> 
> and this:
> `dynamic.6.name=soc_temp dynamic.6.source=/sys/devices/virtual/thermal/thermal_zone0/temp dynamic.6.regexp=(.*) dynamic.6.postprocess=$1/1000 dynamic.6.rrd=GAUGE`
> 
> And still 0:
> ![image](https://user-images.githubusercontent.com/41195917/50817922-86aa9a00-1336-11e9-8a53-8ac463e39244.png)


It is very strange. The wizard of RPi-Monitor can open the file and see the temperature, but then it can not show that information in the Web UI

The last thing that I think you can try is to change the number that identifies the object

```
dynamic.99.name=soc_temp
dynamic.99.source=/sys/devices/virtual/thermal/thermal_zone0/temp
dynamic.99.regexp=(.*)
dynamic.99.postprocess=$1/1000
dynamic.99.rrd=GAUGE
```

Finally, you can try to email the developer to obtain support

**Comment by Leepic** [comment]
@thc2018 Can you give me the content of _/etc/rpimonitor/template/temperature.conf?_ Because I can see that you have two "CPU Temperature". One in cpu.conf which has a value of _zero_ and another probably in temperature.conf which has a value of _null_.

You can try to comment the cpu temperature items in temperature.conf and see what happens.

**Comment by castillo92** [comment]
> @thc2018 Can you give me the content of _/etc/rpimonitor/template/temperature.conf?_ Because I can see that you have two "CPU Temperature". One in cpu.conf which has a value of _zero_ and another probably in temperature.conf which has a value of _null_.
> 
> You can try to comment the cpu temperature items in temperature.conf and see what happens.

He have two CPU temperatures because he copied my template, where Temperatures are inside CPU tab.

@thc2018 try to disable the Temperatures tab to have only one gauge of temperature.

Open de configuration file
`sudo nano /etc/rpimonitor/data.conf`

Write a hashtag before line "temperature.conf"
`#include=/etc/rpimonitor/template/temperature.conf`

Restart RPi-Monitor and I hope it works

**Comment by thc2018** [comment]
Thanks to all!
This helps:

> dynamic.99.name=soc_temp
dynamic.99.source=/sys/devices/virtual/thermal/thermal_zone0/temp
dynamic.99.regexp=(.*)
dynamic.99.postprocess=$1/1000
dynamic.99.rrd=GAUGE
