### ISSUE TITLE
Page becomes inaccessible after a while, serivce needs to be restarted

### ISSUE THREAD

**Issue by Synetech** [XavierBerger/RPi-Monitor#251]
RPi-Monitor (2.12-r0) works for some time (I'm not sure how long), but then the service hangs and the page is no longer accessible. Restarting the service makes it work again, but then after some time it stops and needs to be restarted again.

I wish I could provide more information to help debug this, but I'm not sure where to look. Let me know if there's a log or something I can provide to help because RPi-Monitor is nice, but as it is, it's practically useless if it needs to be manually restarted multiple times per day.

**Comment by Leepic** [comment]
Do you have the error describe in the issue #218 ?

**Comment by Synetech** [comment]
> Do you have the error describe in the issue #218 ?

Actually I do. I just applied the fix from that thread and will see if it hangs again. Thanks for the tip.

**Comment by Synetech** [comment]
It's been running for three days without hanging. That seems to have fixed it. 👍 Thanks!

Hopefully the issue can be fixed in a future version so that it doesn't have to be manually fixed.
