### ISSUE TITLE
Negative swap on the chart

### ISSUE THREAD

**Issue by rostber** [XavierBerger/RPi-Monitor#258]
Negative swap on the chart.
This happened after change the standard value.

https://monosnap.com/file/IoTwVhgAxmQ0mhIlfUZsrSeImrXU35
https://monosnap.com/file/Ehhbw7hzYoDSMS2HrzrqDOX8mHaUg7

Swap in the system:

```
$ swapon -s
Filename				Type		Size	Used	Priority
/dev/zram1                             	partition	262140	0	1
/dev/zram2                             	partition	262140	0	2
/dev/zram3                             	partition	262140	73916	3
/dev/zram4                             	partition	262140	256900	4
```

**Comment by XavierBerger** [comment]
**RPI-Monitor** is a tool you can configure up to your need.
You certainly need to update configuration files.
I'll let you customize it to your need and the close this issue.
