### ISSUE TITLE
E: The repository 'http://giteduberger.fr rpimonitor/ Release' does no longer have a Release file.

### ISSUE THREAD

**Issue by Firesphere** [XavierBerger/RPi-Monitor#267]
Domain seems down

**Comment by thijstriemstra** [comment]
same issue just now: 
```
Genegeerd:3 http://giteduberger.fr rpimonitor/ InRelease                                
Fout:4 http://giteduberger.fr rpimonitor/ Release               
  503  Service Unavailable
```

**Comment by Firesphere** [comment]
Why is this closed without any response?

**Comment by guillaumedavidphd** [comment]
I'd love to have the answer to this question.

**Comment by guillaumedavidphd** [comment]
Okay, I edited `/etc/apt/sources.list.d/rpimonitor.list` and changed the following line from

`deb http://giteduberger.fr rpimonitor/`

to

`deb https://www.giteduberger.fr rpimonitor/`

That was enough to solve the problem and install `rpimonitor`.

**Comment by axl12ap** [comment]
I'm trying to install RPI-monitor using the method on webpage but same error now appears on my raspberry.

when I get the file it contains "http" nor "https", so I tried to edited in https but nothing change, same error of thread title.

Help me please

**Comment by srg-z** [comment]
try another way if this still actual:

custom installation via DEB-pack still working, step-by-step guide correct, just installed.

https://xavierberger.github.io/RPi-Monitor-docs/12_custom_installation.html

**Comment by icolwell** [comment]
Thanks @guillaumedavidphd!
If anyone is looking for an updated/working one-line install script, you can try this:
```
curl -sSL https://raw.githubusercontent.com/icolwell/install_scripts/master/rpimonitor_install.bash | bash
```

Source:
https://github.com/icolwell/install_scripts/blob/master/rpimonitor_install.bash

**Comment by ardinusawan** [comment]
This did the trick https://forums.raspberrypi.com/viewtopic.php?t=255932#p1823865

```
# RPi-Monitor official repository
deb https://www.giteduberger.fr rpimonitor/
```
