### ISSUE TITLE
External links going to external tab in browser?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [XavierBerger/RPi-Monitor#268]
Hello i was wondering if it possible to have a external link in the top bar going to a external tab in the browser. In html it would be <a href="https://www.google.com" target="_blank">google</a> But in raspberry pi and how this is setup I have no clue if this is possible. Can someone help me to figure this out and help to put this in?

Joseph

**Comment by Leepic** [comment]
Hello,

In my knowledge, the only solution is using [Friends](https://xavierberger.github.io/RPi-Monitor-docs/27_configuration_templates.html#friends) link, like this :

- /etc/rpimonitor/data.conf

```
web.friends.1.name=GitHub
web.friends.1.link=https://github.com/XavierBerger/RPi-Monitor/issues/268
```
It's not exactly what you're looking for but it works.

**Comment by Leepic** [comment]
@Therealjosephchrzempiec have you try the Friends solution?

**Comment by XavierBerger** [comment]
No anwser ... closing
