### ISSUE TITLE
Interpolated data?

### ISSUE THREAD

**Issue by patricktokeeffe** [XavierBerger/RPi-Monitor#276]
I see plotted data that appears to be interpolated, but don't understand why. The dynamic interval hasn't been changed (`1` = `10 seconds`) and my source data is updated approximately 10-15 seconds after the start of each minute. 

My data value changes from `4` &rarr; `-99` but the plot shows an intermediate value of `-32.195`. Where does this nonlinear transition come from?

![image](https://user-images.githubusercontent.com/1348834/61075665-54562400-a3cf-11e9-8928-7636c796a2b4.png)

**Comment by XavierBerger** [comment]
You should find your answer in RRD documentation.
This database is doing some average that might explain what you saw.
