### ISSUE TITLE
Use Pi-Sense-Hat for Temperature and Humidity 

### ISSUE THREAD

**Issue by TomJensen1** [XavierBerger/RPi-Monitor#277]
Use Pi-Sense-Hat for Temperature and Humidity 

I would like to use the Pi-Sense Hat for temperature and humidity instead of the DHT sample. Can you briefly describe what would be needed using the DHT11.conf as a starting point? 
I have found that the "Environmental sensors are represented by a LPS25H Pressure/Temperature sensor at address 0x5c and by a HTS221 Humidity/Temperature sensor at 0x5f on the i2c bus." 
if there is something already documenting this, just let me know where to find it.
Thanks to any that respond

**Comment by 4k3or3et** [comment]
Have a look here:

https://github.com/XavierBerger/RPi-Monitor/issues/286
