### ISSUE TITLE
IPC::ShareLite store() error: Invalid argument at /usr/bin/rpimonitord line 840

### ISSUE THREAD

**Issue by MarcleGrand** [XavierBerger/RPi-Monitor#280]
Hello Everyone
Had RPI monitor up and running and all working fine.
I use my RPI for ADS-B reception and ran into an issue on a RPI 3B+ with dump1090 v1.15 mutability. I used the https://forum.flightradar24.com/threads/10232-How-to-Install-dump1090-mutability_1-15-dev-on-RPi bug fix and ran the command sudo wget -O /etc/udev/rules.d/rtl-sdr.rules "https://raw.githubusercontent.com/osmocom/rtl-sdr/master/rtl-sdr.rules"  and sudo reboot which then stopped me from accessing the RPI Monitor. (not able to load in a browser my-RPI-IP:8888  Just says this website can't be reached.
I can reach all other website from my RPI. my-RPI-IP:8754, 10000. 30053 /graphs1090     /dump1090/gmap.html
rpimonitored and systemctl status rpimonitor result in the following:
![Screenshot from 2019-07-21 18-07-27](https://user-images.githubusercontent.com/42249806/61593644-868f2f00-abe2-11e9-9058-26484bd0dc6a.png)
Any ideas what I can do to make this work?
Thanks, Marc

**Comment by Leepic** [comment]
Hello,

Just some questions:

- Which version of RPi-Monitor are you using? 
`rpimonitord -V`
- Is the port 8888 is in LISTEN state?
`ss -nat '( sport = :8888 )'`
- Is rpimonitord really running?
`ps -ef | grep rpimonitord`
- Can you try to launch rpimontord daemon manualy?
Kill it first:
`pkill rpimonitord`
Then launch it by hand:
` /usr/bin/perl /usr/bin/rpimonitord -b /var/run/rpimonitord.pid -l /var/log/rpimonitor.log`

**Comment by MarcleGrand** [comment]
Thanks Leepic.
Hereby the results
![Screenshot from 2019-07-21 21-54-50](https://user-images.githubusercontent.com/42249806/61596339-42138b80-ac02-11e9-8094-6bf549960dc7.png)

**Comment by Leepic** [comment]
The problem it's because RPi-Monitor is not running. The last command has failed because `/var/log/rpimonitor.log` need to be passed as an argument of `-l`, not on a new line but you can launch rpimonitord normally via systemd and tell me if it's working :).

`systemctl start rpimonitor`

**Comment by MarcleGrand** [comment]
Tried `systemctl start rpimonitor` command. The command runs but didn't work (still not able to access the RPI Page via the browser my-RPI-IP:8888)

**Comment by Leepic** [comment]
Hum, OK. RPi-Monitor is probably still not running.
So can you launch rpimonitord by hand:

- run as root user (eg. via sudo)

`sudo /usr/bin/perl /usr/bin/rpimonitord -b /var/run/rpimonitord.pid -l /var/log/rpimonitor.log`

Have you got any errors?

**Comment by MarcleGrand** [comment]
See result below
![Screenshot from 2019-07-22 21-37-46](https://user-images.githubusercontent.com/42249806/61659908-fbd52f80-acc8-11e9-8104-429cfe4f5f84.png)
No other errors as far as I know excet the one when using the `rpimonitored` resulting in IPC::ShareLite store() error: Invalid argument at /usr/bin/rpimonitord line 840
Happy to test anything else you can think off. I already tried to re-install with the same result.

**Comment by Leepic** [comment]
Yes, your bash error is due to the wrong parameter on the command line (because /var/log/rpimonitor.log is not a command, but a file, so bash can execute it). Try this:

```sh
sudo /usr/bin/perl /usr/bin/rpimonitord -b /var/run/rpimonitord.pid -l /var/log/rpimonitor.log
```

Don't forget to put /var/log/rpimonitor.log at the **end** of the command, **not** on a newline.

**Comment by MarcleGrand** [comment]
I found the problem
Doing `sudo nano /etc/rpimonitor/template/network.conf` and blocking (adding # infront) of a `netstat` for port 10000 made my RPI work again.
![Screenshot from 2019-07-22 22-00-19](https://user-images.githubusercontent.com/42249806/61661473-6b98e980-accc-11e9-8fef-3f9940c4da53.png)
I don't think I made a mistake but correct me if I am wrong.
Can this be a bug in the RPI software?

**Comment by Leepic** [comment]
Strange, I've tested and it works for me. If you uncomment it and restart rpimonitord, it's again not accessible?

**Comment by Leepic** [comment]
If everything works for you, you can close this issue :).

**Comment by MarcleGrand** [comment]
Sorry for the late reply. The issue is still present/back again when I edit my `sudo nano /etc/rpimonitor/template/network.conf` and remove the hashes so I put them back.
![Screenshot from 2019-07-28 23-21-29](https://user-images.githubusercontent.com/42249806/62013119-c9c34200-b18e-11e9-9cf4-09fdc79e278d.png)
The only thing I see now is that it will not show the CPU temp. I tried what is mentioned in [https://github.com/XavierBerger/RPi-Monitor/issues/245](url) but haven't succeded yet. Still trying

**Comment by MarcleGrand** [comment]
The only way at the end was to delete and re-install from scratch.
Thanks
