### ISSUE TITLE
one RPi-Monitor support  more than one device ？

### ISSUE THREAD

**Issue by wujunze** [XavierBerger/RPi-Monitor#281]
one RPi-Monitor support  more than one device ？

**Comment by Leepic** [comment]
I'm not sure to understand your question. You're asking if RPi-Monitor can be installed on other hardware than the Raspberry Pi or if it's possible to monitor multiple devices from one RPi-Monitor?

**Comment by Conver** [comment]
He means monitor more than one raspberry from the same interface.

**Comment by XavierBerger** [comment]
Yes. Using SSH, it should work.
**RPI-Monitor** is a tool you can configure up to your need.
I'll let you customize it to your need and the close this issue.
