### ISSUE TITLE
Friends "undefined"

### ISSUE THREAD

**Issue by TristBella** [XavierBerger/RPi-Monitor#284]
I have added the friends as such, but the dropdown shows "undefined".

web.friends.1.title=FriendTitle
web.friends.1.link=http://192.168.1.2:8888/

![image](https://user-images.githubusercontent.com/35009409/62312370-9e24ae00-b453-11e9-85d5-7d350a83632a.png)

**Comment by Leepic** [comment]
I think that the mistake is the title directive (related to the issue #217 ). Have you try like this?

`web.friends.1.name=FriendTitle`
