### ISSUE TITLE
Extra network monitor

### ISSUE THREAD

**Issue by Conver** [XavierBerger/RPi-Monitor#289]
Hello,

I'm trying to add an extra network to the monitor, so that I can see network stats from the VPN connection, but nothing at all is added to the monitor page, can someone tell me what I do wrong here?

The VPN connection interface is tun0

dynamic.10.name=net_received
dynamic.10.source=/sys/class/net/enxb827ebdd259b/statistics/rx_bytes
dynamic.10.regexp=(.*)
dynamic.10.postprocess=$1*-1
dynamic.10.rrd=DERIVE
dynamic.10.max=0

dynamic.11.name=net_send
dynamic.11.source=/sys/class/net/enxb827ebdd259b/statistics/tx_bytes
dynamic.11.regexp=(.*)
dynamic.11.postprocess=
dynamic.11.rrd=DERIVE
dynamic.11.min=0

dynamic.12.name=vpn_received
dynamic.12.source=/sys/class/net/tun0/statistics/rx_bytes
dynamic.12.regexp=(.*)
dynamic.12.postprocess=$1*-1
dynamic.12.rrd=DERIVE
dynamic.12.max=0

dynamic.13.name=vpn_send
dynamic.13.source=/sys/class/net/tun0/statistics/tx_bytes
dynamic.13.regexp=(.*)
dynamic.13.postprocess=
dynamic.13.rrd=DERIVE
dynamic.13.min=0

web.status.1.content.8.name=Network
web.status.1.content.8.icon=network.png
#web.status.1.content.8.line.1="To activate network monitoring, edit and customize <font color='#AA0000'><b>network.conf</b></font>"
#web.status.1.content.8.line.2="Help is available in man pages:"
#web.status.1.content.8.line.3="<font color='#AA0000'><b>man rpimonitord</b></font> or <font color='#AA0000'><b>man rpimonitord.conf</b></font>"
web.status.1.content.8.line.1="Ethernet Sent: <b>"+KMG(data.net_send)+"<i class='icon-arrow-up'></i></b> Received: <b>"+KMG(Math.abs(data.net_received)) + "<i class='icon-arrow-down'></i></b>"

web.status.2.content.8.name=Network
web.status.2.content.8.icon=network.png
#web.status.1.content.8.line.1="To activate network monitoring, edit and customize <font color='#AA0000'><b>network.conf</b></font>"
#web.status.1.content.8.line.2="Help is available in man pages:"
#web.status.1.content.8.line.3="<font color='#AA0000'><b>man rpimonitord</b></font> or <font color='#AA0000'><b>man rpimonitord.conf</b></font>"
web.status.2.content.8.line.1="VPN Sent: <b>"+KMG(data.vpn_send)+"<i class='icon-arrow-up'></i></b> Received: <b>"+KMG(Math.abs(data.vpn_received)) + "<i class='icon-arrow-down'></i></b>"

**Comment by Conver** [comment]
Isn't there no one who can asset me with this?

**Comment by Simon01011** [comment]
Hi!

A little bit late, but you can do:

web.status.1.content.8.name=Network
web.status.1.content.8.icon=network.png
web.status.1.content.8.line.1="Ethernet Sent: "+KMG(data.net_send)+" Received: "+KMG(Math.abs(data.net_received)) + ""
web.status.1.content.8.line.2="VPN Sent: "+KMG(data.vpn_send)+" Received: "+KMG(Math.abs(data.vpn_received)) + ""`
