### ISSUE TITLE
How to debug low values?

### ISSUE THREAD

**Issue by slowrunner** [XavierBerger/RPi-Monitor#291]
One of my RPI-Monitor dynamic variables is a battery voltage measurement of my robot.  I am certain the voltage never falls below 7.2v, but RPI-Monitor is occasionally stuffing a value near zero into the database:
```
<!-- 2019-09-17 19:01:00 EDT / 1568761260 --> <row><v>6.810889240e-01</v></row>
```
 RPI-Monitor is configured with:
```
dynamic.1.name=carl_vbatt
dynamic.1.source=/home/pi/Carl/plib/vBatt.py
# daemon.delay=30s runs twice a minute
dynamic.1.regexp=(.*)
dynamic.1.postprocess=sprintf("%.2f", $1)
dynamic.1.min=5
dynamic.1.rrd=GAUGE 

web.statistics.1.content.8.name=Battery
web.statistics.1.content.8.graph.1=carl_vbatt
web.statistics.1.content.8.ds_graph_options.carl_vbatt.label=Battery Voltage (Volts)
```

vBatt.py reads the battery voltage which ranges from 12 volts down to 8.1 volts in normal operation.  If it were ever below 7.2v the robot would shutdown.

There is a test in vBatt.py to log if the measured voltage is ever low, and have no low voltage events logged.

Also why would there be a value less than 5 - considering the "min=5" line?

I leave an RPI-Mon tab "open" in Chrome Browser on a Mac, and sometimes the Mac goes to sleep. 

<img width="907" alt="RPI-Monitor_vBatt_LowV" src="https://user-images.githubusercontent.com/8950202/65087909-7ba80f00-d985-11e9-998a-5af3ebd0f312.png">

How can I debug this?

**Comment by GhislainOlitec** [comment]
You can use rrdtools. dump the rrd file to an xml file. You can edit the xml with a normal text editor. and use restore to recreate the rrd file.

Don't forget to stop rpimonitor

rrdtool dump wifi_received.rrd wifi_test.xml

rrdtool restore wifi_test.xml wifi_received.rrd
