### ISSUE TITLE
Unedefined in title top3 add-on

### ISSUE THREAD

**Issue by 53645714n** [XavierBerger/RPi-Monitor#292]
Picture says it all.
![undefined in title top3 add-on](https://user-images.githubusercontent.com/44052459/66488631-851d2680-eaae-11e9-884e-f69f495e2e21.png)

I tried all options in data.conf like 'web.addons.5.showTitle=0', 'web.addons.5.showtitle=0', 'web.addons.5.showTitle=false' and 'web.addons.5.showtitle=false' but it keeps showing up.

**Comment by Leepic** [comment]
Hello,

Can you give me your data.conf?

**Comment by XavierBerger** [comment]
No answer , closing
