### ISSUE TITLE
repository is down

### ISSUE THREAD

**Issue by mushu999** [XavierBerger/RPi-Monitor#294]
pi@pihole:~ $ sudo apt update && sudo apt upgrade -y && exit
Get:1 http://archive.raspberrypi.org/debian buster InRelease [25.2 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Ign:3 http://giteduberger.fr rpimonitor/ InRelease
Err:4 http://giteduberger.fr rpimonitor/ Release
  Redirection loop encountered
Reading package lists... Done
E: The repository 'http://giteduberger.fr rpimonitor/ Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
pi@pihole:~ $

**Comment by XavierBerger** [comment]
Server is working and has no reveal any problem.

Closing this issue.

**Comment by guillaumedavidphd** [comment]
Same problem here. Same output. I followed the instructions in the documentation down to the T.
Suggestions?

**Comment by guillaumedavidphd** [comment]
Solved, check out #267.
