### ISSUE TITLE
Can not get information (dynamic.json) from RPi-Monitor server.

### ISSUE THREAD

**Issue by ghost** [XavierBerger/RPi-Monitor#297]
Raspberry Pi 4, raspberrypi 4.19.85-v8+, Raspbian, the error always shown up on every boot http://raspberrypi.local:8888.

So I should restart service on every boot, then it work. Any suggestion to solve this problem?

**Comment by Leepic** [comment]
Same issue describe in #302.
Can you try the changes in #293 and tell us if it works?

**Comment by ghost** [comment]
Hello @Leepic,

Sorry for my late. I tried both of #302 and #293 but It doesn't work in my Raspberrypi 4.19.102-v8+, Raspbian.
