### ISSUE TITLE
After few hours i can't access rpimonitor via http://raspberrypi.local:8888

### ISSUE THREAD

**Issue by zblast5000** [XavierBerger/RPi-Monitor#299]
After few hours i can't access rpimonitor via  http://raspberrypi.local:8888, when i try run rpimonitord i receive the message:
[2019/11/30-08:10:39] RPi-Monitor has been started
Log level can be increased or decreased during runtime
by sending signal USR1 or USR2 with the command killall -USRx rpimonitord
Web server not started because of error: Address already in use
rpimonitord stopped because respawning too fast.
i use RPI3 B+ and in have installed a apache server in raspbian debian.

**Comment by brantje** [comment]
Same here with the docker image. Sometimes i just get a gateway timeout (using reverse proxy).

**Comment by uksbi** [comment]
Same here in raspberry light (FR24 image). It looks like that it's happened after 8 hours.

**Comment by Leepic** [comment]
Can you tell me if you have the errors describe in #218 ?

**Comment by XavierBerger** [comment]
no answer, closing
