### ISSUE TITLE
Docker Swarm. Show all nodes

### ISSUE THREAD

**Issue by Ivanjn** [XavierBerger/RPi-Monitor#306]
Hi
I just installed rpi-monitor in a 4 nodes #docker swarm and it works great. But only shows info about raspberry pi is running on. Is it possible to shows all nodes info?

**Comment by XavierBerger** [comment]
Yes, using ssh, it should work.
Remember, **RPI-Monitor** is a tool you can configure up to your need.
I'll let you customize it to your need and the close this issue.
