### ISSUE TITLE
Change temp from C to F

### ISSUE THREAD

**Issue by maserowik** [XavierBerger/RPi-Monitor#307]
Is there a way to change the temp from Celsius to Fahrenheit on the webpage?
Thanks
Mike

**Comment by Simon01011** [comment]
I don't know how to do it in the web interface. But of course you can change the config file for temperature. It's in /etc/rpimonitor/template. Edit line 14 to something like
`dynamic.12.postprocess=sprintf("%.2f", $1/1000*9/5+32)`
This is untested but should work. From now on the data is stored in °F and shown like that in the webpage.
