### ISSUE TITLE
Release file no longer available, can't check for updates, domain is invalid

### ISSUE THREAD

**Issue by Synetech** [XavierBerger/RPi-Monitor#339]
The giteduberger.fr domain is now a site for a B&B, so package update checks will now fail. 😕 (Which in turn, blocks updates to other things like PiHole, so RPi-Monitor's source file needs to be deleted or the line referencing giteduberger.fr commented out.)

**Comment by XavierBerger** [comment]
It has always been like this.
So now, if you want to rent a flat for skiing or mountain hiking in the french alps, you know where to go :-)

**Comment by Synetech** [comment]
Hmm, that's strange. Yesterday, apt-get update kept complaining that giteduberger.fr had no Release file. Today it's working again. 🤔
