### ISSUE TITLE
Update Issues

### ISSUE THREAD

**Issue by zahroc** [XavierBerger/RPi-Monitor#351]
When I try to update via sudo apt update, I get the following:

Err:6 http://giteduberger.fr rpimonitor/ Release
  Redirection loop encountered
Reading package lists... Done
E: The repository 'http://giteduberger.fr rpimonitor/ Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by telemaxx** [comment]
https://github.com/XavierBerger/RPi-Monitor/issues/326

**Comment by zahroc** [comment]
Issue Solved
