### ISSUE TITLE
The repository 'https://giteduberger.fr rpimonitor/ Release' no longer has a Release file.

### ISSUE THREAD

**Issue by MatthK** [XavierBerger/RPi-Monitor#357]
I just installed RPi-Monitor using the getting started guide and now have the problem that my `sudo apt update` doesn't work anymore.

I do get the following error message:

```
pi@Pihole:~ $ sudo apt update
Hit:1 http://packages.microsoft.com/repos/code stable InRelease
Hit:2 http://archive.raspberrypi.org/debian buster InRelease
Hit:3 http://raspbian.raspberrypi.org/raspbian buster InRelease
Ign:4 https://giteduberger.fr rpimonitor/ InRelease
Err:5 https://giteduberger.fr rpimonitor/ Release
  Redirection loop encountered
Reading package lists... Done
E: The repository 'https://giteduberger.fr rpimonitor/ Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

How can I get the update working again?

**Comment by carlosala** [comment]
Same issue, I have just commented the line of this repo (in `/etc/apt/sources.list.d/rpimonitor.list`, or in the file `/etc/apt/sources.list`).
It seems like the repo doesn't work, it's better to disable the repo until @XavierBerger fixes it.

**Comment by telemaxx** [comment]
https://github.com/XavierBerger/RPi-Monitor/issues/354

just change "http:" to "https:" inside rpimonitor.list

**Comment by MatthK** [comment]
It still does not work. This is my /etc/apt/sources.list.d/rpimonitor.list file:

```
# RPi-Monitor official repository
deb https://giteduberger.fr rpimonitor/
```
And with that, I do get the error message.

**Comment by pkloehn1** [comment]
Putting the trailing '/' behind the domain allowed the install to complete for me.

`# RPi-Monitor official repository
deb https://giteduberger.fr/ rpimonitor/`

**Comment by MatthK** [comment]
That indeed did the trick. Thanks.

**Comment by ardinusawan** [comment]
This did the trick https://forums.raspberrypi.com/viewtopic.php?t=255932#p1823865

```
# RPi-Monitor official repository
deb https://www.giteduberger.fr rpimonitor/
```
