### ISSUE TITLE
RRD customisation

### ISSUE THREAD

**Issue by tigrrr** [XavierBerger/RPi-Monitor#365]
How can I define the RRD size as well as resolution of the rrd tables in the config file ? I can't find this in the raspiconfig.conf settings anymore, in the arch.conf I can see these instructions, but they dont seem to have any actual effect.. the rrd files creation/size is not affected when using theese settings.. ? 

edit: resolved, found the config file in the /usr/bin/raspimond, where the RRD create definitions are located.

**Comment by realpixelcode** [comment]
> edit: resolved

Great! Please close the issue :)
