### ISSUE TITLE
Is it possible to force the y-axis graph in statistics to start at 0 ?

### ISSUE THREAD

**Issue by gilarelli** [XavierBerger/RPi-Monitor#370]
Hello,

Does a parameter exists to force the y-axis graph in statistics to start at 0 ?
Is it possible at all beside (maybe) adding another data set to 0 ?

What I have :
![image](https://user-images.githubusercontent.com/67586076/122213260-0f837380-cea9-11eb-9b20-c05737b92a42.png)

What I want :
![image](https://user-images.githubusercontent.com/67586076/122213832-ae0fd480-cea9-11eb-8c2c-606b26eb0858.png)

Thanks!

**Comment by psa-jforestier** [comment]
hello
Here is a sample line of my conf file :
`web.statistics.2.content.1.graph_options.y2axis={ position: "right", min: 0, max: 100 }`

**Comment by gilarelli** [comment]
Thanks for telling me where to look for an answer !

This did the trick for me : 
![image](https://user-images.githubusercontent.com/67586076/130861996-98ca6bfc-10f0-4538-9323-560073dd808a.png)
![image](https://user-images.githubusercontent.com/67586076/130862630-2c104070-19ac-4012-8189-33f24e424290.png)
