### ISSUE TITLE
RPi Monitor Repository Down?

### ISSUE THREAD

**Issue by davmc123** [XavierBerger/RPi-Monitor#384]
I get the following error appearing when I run 'apt update'

W: Failed to fetch http://giteduberger.fr/rpimonitor/InRelease  500  Internal Server Error [IP: 213.186.33.17 80]

**Comment by palve55** [comment]
Me too...

**Comment by telemaxx** [comment]
me2

**Comment by octoworld** [comment]
me2²

**Comment by XavierBerger** [comment]
Fixed. Thanks for feedback and sorry for the issue
