### ISSUE TITLE
Can't update RPi Monitor

### ISSUE THREAD

**Issue by Machou** [XavierBerger/RPi-Monitor#391]
Hello

When i want update RPi Monitor on Raspbian, i have this error :

Err :6 http://giteduberger.fr rpimonitor/ InRelease
  Connexion à giteduberger.fr: 80 (213.186.33.17) impossible. - connect (113: Aucun chemin d'accès pour atteindre l'hôte cible)

**Comment by marapavelka** [comment]
Edit /etc/apt/sources.list.d/rpimonitor.list and change line `deb http://giteduberger.fr rpimonitor/` to `deb https://www.giteduberger.fr rpimonitor/`

**Comment by Machou** [comment]
I have this error now :

Err :10 https://www.giteduberger.fr rpimonitor/ InRelease
  Connexion à www.giteduberger.fr: 443 (213.186.33.17) impossible. - connect (113: Aucun chemin d'accès pour atteindre l'hôte cible)

`cat /etc/apt/sources.list.d/rpimonitor.list`

```bash
# RPi-Monitor official repository
deb https://www.giteduberger.fr rpimonitor/
```
