### ISSUE TITLE
'http://giteduberger.fr rpimonitor/ Release' no longer has a Release file

### ISSUE THREAD

**Issue by apeelme** [XavierBerger/RPi-Monitor#399]
![image](https://user-images.githubusercontent.com/868203/180377555-22968af4-3fce-401c-b5ef-17a91022b532.png)

![image](https://user-images.githubusercontent.com/868203/180377837-a426b527-81a4-4353-9a9e-1e1dfef4d45b.png)

**Comment by Shrekmachine** [comment]
same here since today

**Comment by apeelme** [comment]
any news???

**Comment by Shrekmachine** [comment]
today all good again. no error message
