### ISSUE TITLE
Err:5 http://www.giteduberger.fr rpimonitor/ InRelease 

### ISSUE THREAD

**Issue by earlywaff** [XavierBerger/RPi-Monitor#403]
I get the following error appearing when I run 'apt update'

W: Failed to fetch http://giteduberger.fr/rpimonitor/InRelease 500 Internal Server Error [IP: 213.186.33.17 80]

**Comment by marapavelka** [comment]
Same for me since yesterday :(

**Comment by adi170-alt** [comment]
same :(

**Comment by XavierBerger** [comment]
It should be fixed now.
@earlywaff Can you check and close your comment if it is effectively fixed?

**Comment by earlywaff** [comment]
Thanks for the quick fix! Everything works:)
