### ISSUE TITLE
Authentication for RPi-Monitor

### ISSUE THREAD

**Issue by dedunumax** [XavierBerger/RPi-Monitor#52]
Isn't it worth to develop authentication module? I can develop it if it is worth.

Thank you.

**Comment by typhoon71** [comment]
How is this one going? Just asking.
If there's auth, one could use stunnel and be happy/secure without having to configure a reverse proxy.
Other programs have login only (like transmission-daemon), and the easy way to secure them is to enable auth and have the daemon listen on localhost only, then stunnel it. and stunnel is really easy to set.

**Comment by abhigyan17** [comment]
there will be many scripts or webmin addons available to put authentication on a particular port 8888. Need to search for that

**Comment by XavierBerger** [comment]
A solution exists with `nginx` configuration explained here : [http://rpi-experiences.blogspot.fr/2013/05/rpi-monitor-security-and-authentication.html](http://rpi-experiences.blogspot.fr/2013/05/rpi-monitor-security-and-authentication.html)
