### ISSUE TITLE
Duplicate statistics + status when .conf placed in /etc/rpimonitor

### ISSUE THREAD

**Issue by Flint4** [XavierBerger/RPi-Monitor#68]
Hi, 

I've found out that statistics and status are shown twice when the .conf file is placed in  /etc/rpimonitor instead of  /etc/rpimonitor/template. 

To reproduce: move a file like cpu.conf from /etc/rpimonitor/template to /etc/rpimonitor and change in data.conf the path to include=/etc/rpimonitor/cpu.conf. Then sudo service rpimonitor restart and see the result in the web browser. 

![Status](https://cloud.githubusercontent.com/assets/9900799/5154593/cf93b3b2-7265-11e4-9883-f53f80e61c35.jpg)
![Statistics](https://cloud.githubusercontent.com/assets/9900799/5154594/e0550fde-7265-11e4-8b6e-3da900676c62.jpg)

RPi-Monitor Version 2.9

Best wishes, 
Alex

**Comment by XavierBerger** [comment]
Fixed in version 2.10. 
Now **RPi-Monitor** reads only `/etc/rpimonitor/daemon.conf` and `/etc/rpimonitor/data.conf`
