### ISSUE TITLE
Statistics Date Range

### ISSUE THREAD

**Issue by rexpark** [XavierBerger/RPi-Monitor#70]
This isn't a bug, more of a question. Is it possible to modify the scale and date range options on the Statistics graphs? IE, I'd like a 60s 5 day graph.

I've done a quick dig through the source code and I can't seem to find where those options are even defined.

**Comment by XavierBerger** [comment]
Version 2.11 is available as beta in devel repository and is coming with a new feature: RRD customization.
It is then now possible to define the format of RRD in configuration file. The configuration can be done per data and can be different for each one.
If you want to try that, I do invite everyone to try the version beta from RPi-Monitor-deb repository.

**Comment by XavierBerger** [comment]
Version 2.11 beta (and release soon) is fixing this issue. I'm then closing this issue. Plaese report your comments on issue #94.
