### ISSUE TITLE
Make better usage of larger screens

### ISSUE THREAD

**Issue by tichris0** [XavierBerger/RPi-Monitor#77]
I'm loading it on a 1080p screen and the space isn't used very well.  I've added extra styling and made very small changes to the html so that it can support multiple columns when the screen is large enough.  I've attached my patches in case you wanted to take them Vanilla.  If not; I'd love to see a design that doesn't waste so much horizontal space on large screens.

rpimonitor.css:
```
92a93,118
> .row {
>   display: inline-block;
> }
>
> @media screen and (min-width: 1024px) {
>   .column-fluid {
>     -webkit-column-rule: 1px solid #f0f0f0;
>     -moz-column-rule: 1px solid #f0f0f0;
>     column-rule: 1px solid #f0f0f0;
>   }
> }
> @media screen and (min-width: 1024px) and (max-width: 1526px) {
>   .column-fluid {
>     -webkit-column-count: 2;
>     -moz-column-count: 2;
>     column-count: 2;
>   }
> }
> @media screen and (min-width: 1526px) {
>   .column-fluid {
>     -webkit-columns-count: 3;
>     -moz-column-count: 3;
>     column-count: 3;
>   }
> }
>
```

status.html.patch:
```
42d41
<     <div class="container-fluid">
45a45
>     <div class="container-fluid column-fluid">
66d65
<
```

**Comment by XavierBerger** [comment]
Very nice and easy to implement. It is already in devel branch and will be a feature of v2.11.
Thanks.
