### ISSUE TITLE
Multiple graphs per page

### ISSUE THREAD

**Issue by ABrolund** [XavierBerger/RPi-Monitor#80]
Not an issue,  it's an enhancement request. 
As RPI Monitor is quick and reliable it is not ony used for monitoring the raspberry itself. 
I use it for collecting weather data as well. 
But here it comes as pressure (around 1000mb) is far away from temperature (around 20°C)  I would like to have two graphs in one page. One with temperature and one pressure data. 
Maybe this is already possible and I overlooked it ?

**Comment by XavierBerger** [comment]
This feature is already existing. RPi-Monitor is able to manage dual axis you can then draw pressure and temperature on the same graph or temperature and humidity as describe in my blog in the article about DHT11/22.
