### ISSUE TITLE
shellinabox addon without ssl

### ISSUE THREAD

**Issue by firewire789** [XavierBerger/RPi-Monitor#81]
Hey, thank you for your great application. Sorry for my English, I'm not a native speaker.

My question is, if it is possible to open the addon shellinabox without https. I want to disable ssl of shellinabox, and after that of course the addon within the web interface doesn't work because of a https connection in the iframe. I can't find the configuration for that within the rpimonitor conf files.
Thank you for your help.

**Comment by XavierBerger** [comment]
1/ RPi-Monitor is just displaying shellinabox and do not bring any customisation to this software. This is then not the good location to ask such a question.
2/ It is not recommanded to not use SSL to initiate a connection to your PC. Your password will be in plain text.
3/ You should try to acess directly to shellinabox and accept the certificate. Then the integration of shellinabox into RPi-Monitor interface should work.
