### ISSUE TITLE
Information not being updated

### ISSUE THREAD

**Issue by jepolch** [XavierBerger/RPi-Monitor#85]
Xavier, on one of my Pi's (B+, latest Wheezy) the information on the screen is not correct. For instance, although the Pi is overclocked (900 Mhz), the screen shows 700 Mhz. Also, it states that 13 packages need to be updated. I ran 'apt-get update' and upgrade, rebooted, and still it shows the wrong info. I ran 'apt-get dist-upgrade', rebooted, still shows I need updates. I also cleared my browser cache and cookies, still not right. Please see:
![rpim](https://cloud.githubusercontent.com/assets/11262109/6433585/af9575fe-c040-11e4-9474-3eb7efd40c0d.jpg)

**Comment by XavierBerger** [comment]
Update is done once a day by cron. If you want to change this behavior, call /usr/share/rpimonitor/scripts/updatePackagesStatus.pl when needed.
