### ISSUE TITLE
Actual CPU usage

### ISSUE THREAD

**Issue by typhoon71** [XavierBerger/RPi-Monitor#90]
Actual CPU usage should be added to the default CPU monitor.
I have a  3% average for 1/5/15 min right now, intensive usage.
The real important info is that my CPU is 100% (from top/htop).
Could this be added? Thanks.

**Comment by XavierBerger** [comment]
Load average is not percentage but number of process waiting to be processed by CPU (I let you check the Onternet for explaination). If your number is equal to 3, I'm not surprise to hear that CPU is working at 100%. This number should not excedd the number of processing unit: 1 for the Rapberry Pi.
The CPU could got to 100% during a short time and is not reflecting a high usage of CPU. If you take a measure of CPU at this time, you will think that your CPU is overloaded wil in reallity you di measure the CPU usage during a period of usage.
