### ISSUE TITLE
Upgradable packages aren't updated

### ISSUE THREAD

**Issue by Germain67** [XavierBerger/RPi-Monitor#92]
Hello,
I've found that upgradable packages listed on the status page were never updated (the same packages are always listed, even after sudo update & upgrade).

http://i.imgur.com/FKDXVfL.png

Do you have any idea to fix this ?

Thank you in advance,
Germain

**Comment by XavierBerger** [comment]
This is not a **RPi-Monitor** question but a question more related to debian based distro. I think thet the comma you are looking for is `sudo apt-get dirst-upgrade`. You can also use `aptitude` instead of `apt-get`.

**Comment by Germain67** [comment]
Even with your command it didn't changed anything.
http://i.imgur.com/ZOazSgg.png

In fact, updates are done, 
but for a reason I ignore the old updates are still listed in rpimonitor (and the new ones aren't listed).

**Comment by XavierBerger** [comment]
Your probleme is a desynchronization between RPi-Monito and the packages. I let you read why and how to fix it in the FAQ: http://rpi-experiences.blogspot.fr/p/rpi-monitor-faq.html

**Comment by Germain67** [comment]
Thank you it's working now ! :)

**Comment by XavierBerger** [comment]
Have a look on the Internet to understand how cron is working and how to write an init script. And you will find your solution...

**Comment by woodytheledge** [comment]
I had the same issue... I ran this command and it seems to work.. 

Sudo /usr/share/rpimonitor/scripts/updatePackagesStatus.pl
