### ISSUE TITLE
Why 3 process ?

### ISSUE THREAD

**Issue by vrampal** [XavierBerger/RPi-Monitor#93]
Hello,

Apparently RPi-Monitor start 3 process, 1 for polling/monitoring, 1 for http server (if enable) and a 3rd one I don't understand.
Could you please explain ?

Regards,
Vincent

**Comment by XavierBerger** [comment]
One main process starting pooling (as root) and http server (as unprivilegied user). 
This main process is also checking if these both process are running and is restarting them in case of issue.
