### ISSUE TITLE
Feature Request: Whitespace in Status Layout

### ISSUE THREAD

**Issue by dschaper** [XavierBerger/RPi-Monitor#95]
Current status layout in 3 panel display leaves whitespace to the left of section heading icons with the graph below the section heading:
![741ac3f0-0deb-11e5-8c73-dd4d91a9c4ed](https://cloud.githubusercontent.com/assets/2782850/8091056/404055be-0f66-11e5-8292-d54a40d89691.JPG)

Possibly move graphs to the left in the whitespace to compact the layout and create a better visual flow
![c06d6096-0deb-11e5-9239-2690cc6f5bd8](https://cloud.githubusercontent.com/assets/2782850/8091068/59c1dcc4-0f66-11e5-8943-5f1bfc478cc2.png)

**Comment by XavierBerger** [comment]
Good news, this feature is already implemented but it may be visible or no depending on the size of the screen.
In fact, this feature may need some fine tuning. Everything is located into the file `rpimonitor.css`. 
The parameter `width` of `.Title` defines the size of left title (icon + Temperature in your example).
The parameter `width` of `.Text` defenes the size of information on right (or under): the gauge.
Finally, the parameters `@media screen and ...` define how the columns are rendered.
All these parameters have impact on how the information are displayed.

So, if you find some value that have a better render on screen, I'll be happy to integrate this on the next release.
Please describe the size of your screen and the expected result if you propose new values.

**Comment by dschaper** [comment]
Okay, I'll have to refresh on my css and layout flow, but I'll take a look and report back what I find.

Thanks!
