### ISSUE TITLE
A few things i missing

### ISSUE THREAD

**Issue by bismosa** [XavierBerger/RPi-Monitor#99]
Hello,

i think that is not the right place...please delete if it is so. But i dont find out how can i contact you.
I don´t want to create for each point a Issue...or should i do that? (I have created two Issues that i have found)

1.) How can i ask questions? Is there a Forum? 
2.) Feature Request (?) Examples from other users / Place to create examples
It is very hard for me to find out the exact regex...and a few examples are very helpful. 
I have created a external script on my second Raspberry with Openelec to transmit this values to the first Raspberry...so i can display this values to. Maybe someone is interested?
3.) Number by static.XX / dynamic.XX / content.XX  -> Is there a way to easily find out which the next free number is? Or can i use  from number 50 for my own extensions?
What happens when a number is used more than once?
4.) Is there somewhere a log file? I cant find one. Than it is very hard to find a fault in the configuration.   

THANK YOU VERY MUCH!

Regards,
Sascha

**Comment by XavierBerger** [comment]
1.)You can open a topic in forum of raspberrypi.org, I think it would be the best place. (once a topic is open, you can add a comment in this issue to let us know its existence.)
2.) Feature request should come here. 
2.) to define the exact regex, try `rpimonitord -i`, look documentation on the Internet about regex and see my blog for examples of **RPi-Monitor**
3.) Indexes (XX) should be unique per KPI and per file.
Originally there were supposed to be unique overall the configuration and that why sometime the index are still greater that 1 into files.
4.) Log file will be introduce in next version: v2.11 (available in beta)
